Add ability to build images within Openstack
kubernetes-sigs/image-builder pull request #1013
Opened 2022-11-03 11:34 UTC by drew-viles

What this PR does / why we need it:
**First PR in the project so apologies in advanced if anything is missing/needs adding**

This PR is for adding Openstack image building into the image builder. It allows a user/pipeline to build an image in Openstack which could be useful for people wanting directly build in an instance allowing them to do additional things such as baking in GPU drivers and more.
It uses the Openstack packer plugin to create an instance from a source image located in Openstack, build the image using this repo, and then create the image from the volume.

This has been through a number of iteration in the forked repo we have and has been tested on multiple version of K8s using Ubuntu 20.04 and 22.04

Example run:
```
hack/ensure-ansible.sh
Starting galaxy collection install process
Nothing to do. All requested collections are already installed. If you want to reinstall them, consider using `--force`.
hack/ensure-packer.sh
hack/ensure-goss.sh
Right version of binary present

{...snip...}

==> openstack: Creating the image: ubuntu-2204-kube-v1.23.10
    openstack: Image: 8e3a00ea-b11c-44b2-9093-20327e9357e0
==> openstack: Waiting for image ubuntu-2204-kube-v1.23.10 (image id: 8e3a00ea-b11c-44b2-9093-20327e9357e0) to become ready...
==> openstack: Updating image visibility to private
==> openstack: Deleted temporary floating IP 'f4a9fa0c-9128-40f0-876f-85ad039b0b53' (IP_ADDRESS)
==> openstack: Terminating the source server: 96233dfa-72a0-436f-97d2-cc2d1515bc8f ...
==> openstack: Deleting volume: fe87f78e-651d-4a32-bf9d-3464b46dff04 ...
==> openstack: Deleting temporary keypair: packer_635ff270-8d5f-e902-8306-a94429006b60 ...
==> openstack: Running post-processor: custom-post-processor (type shell-local)
==> openstack (shell-local): Running local shell script: /tmp/packer-shell958982601
Build 'openstack' finished after 8 minutes 58 seconds.

==> Wait completed after 8 minutes 58 seconds

==> Builds finished. The artifacts of successful builds are:
--> openstack: An image was created: IMAGE_ID
--> openstack: An image was created: IMAGE_ID
```

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #
None to my knowledge

**Additional context**
Add any other context for the reviewers

2022-11-03 11:53 UTC, drew-viles commented
I've opened a few of these in the past few days and then closed them after noticing some best practices were not followed. 

My apologies for that!

I'm confident we'll be ok to go ahead with this one though so I'll leave it be. (Unless I need to rebase with any new commits before it's hopefully approved and merged).

Thanks!

2022-11-09 21:10 UTC, Jeremy-Boyle commented
Thank you for adding this ! This does look pretty cool !

2022-11-24 11:27 UTC, drew-viles commented
Hi @mdbooth and/or @codenrhoden

Are you able to take a look at this when you get a moment please?
Thanks!

2022-11-25 17:20 UTC, mnaser requested changes
good stuff initially, we'll contribute Flatcar support as well to your branch, so hopefully we can land that together.

2022-11-25 17:20 UTC, mnaser commented on docs/book/src/capi/providers/openstack-remote.md
> +
are you sure that the Packer client needs the Python OpenStack client to work?

2022-11-25 17:20 UTC, mnaser commented on docs/book/src/capi/providers/openstack-remote.md
> +> Other OS's will be supported at a later time.
our team (cc @okozachenko1203) would want to get Flatcar support in out of the box, we will work on a PR to your branch.

2022-11-25 17:20 UTC, mnaser commented on docs/book/src/capi/providers/openstack-remote.md
> +## Setup Openstack authentication
Would it make sense to instead link to https://developer.hashicorp.com/packer/plugins/builders/openstack#configuration-reference and mention that since we're using Packer?

2022-11-25 17:20 UTC, mnaser commented on docs/book/src/capi/providers/openstack-remote.md
> +From the `images/capi` directory, run `PACKER_VAR_FILES=var_file.json make build-openstack-ubuntu-xxxx`.
I would un-hardcode the ubuntu bits here since we will have (hopefully) Flatcar.

2022-11-25 17:20 UTC, mnaser commented on docs/book/src/capi/providers/openstack-remote.md
> +An instance is built in Openstack from the source image defined and once completed, the instance is shutdown and the volume uploaded into an image that can then be used.
```suggestion
An instance is built in Openstack from the source image defined and once completed, the instance is shutdown and the image gets created that can then be used afterwards.
```

2022-11-25 17:20 UTC, mnaser commented on docs/book/src/capi/providers/openstack-remote.md
> +This image will default to private and will need to be set as shared or public to be used by other projects within Openstack.
You should mention that `image_visibility` can control this.

2022-11-25 17:20 UTC, mnaser commented on images/capi/Makefile
> +#TODO    hack/ensure-openstack.sh
don't think this is necessary

2022-11-25 17:20 UTC, mnaser commented on images/capi/Makefile
> +build-openstack-all: $(OPENSTACK_BUILD_TARGETS)
we'll add flatcar to that

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/config/kubernetes.json
> +  "kubernetes_deb_version": "1.24.3-00",
I think we shouldn't touch this in this change since it isn't part of the PR

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/config/kubernetes.json
> +  "kubernetes_series": "v1.24",
same here.

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/openstack/OWNERS
> +  - cluster-api-cloudstack-maintainers
I'd drop cloudstack here

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/openstack/OWNERS
> +  - image-builder-cloudstack-reviewers
and here too maybe?

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/openstack/packer.json
> +    },
the first boot playbooks is actually noop for qemu and only really does something for VMware, so we can fully avoid these steps and go straight for nodes.

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/openstack/packer.json
> +        "ANSIBLE_SSH_ARGS='{{user `existing_ansible_ssh_args`}} -oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa -o IdentitiesOnly=yes'"
note for reader: the `+ssh-rsa` stuff is needed bc of OpenSSH 9 users

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/openstack/packer.json
> +      "image_disk_format": "raw",
please make this a configurable variable

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/openstack/packer.json
> +      "use_blockstorage_volume": true,
please make this a configurable option

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/openstack/packer.json
> +      "volume_size": "10"
please make this a configurable option

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/openstack/packer.json
> +    "accelerator": "kvm",
let's drop this here, not used

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/openstack/packer.json
> +    "cpus": "1",
let's drop this here, not used

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/openstack/packer.json
> +    "disk_compression": "false",
let's drop this here, not used

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/openstack/packer.json
> +    "disk_discard": "unmap",
let's drop this here, not used

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/openstack/packer.json
> +    "disk_size": "20480",
let's drop this here, not used

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/openstack/packer.json
> +    "firmware": "",
let's drop this here, not used

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/openstack/packer.json
> +    "format": "qcow2",
let's drop this here, not used

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/openstack/packer.json
> +    "headless": "true",
let's drop this here, not used

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/openstack/packer.json
> +    "http_directory": "./packer/openstack/linux/{{user `distro_name`}}/http/",
let's drop this here, not used

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/openstack/packer.json
> +    "memory": "2048",
let's drop this here, not used

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/openstack/packer.json
> +    "qemu_binary": "qemu-system-x86_64",
let's drop this here, not used

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/qemu/packer.json
> +        "'-O'",
since this is unrelated to this, lets drop this from the PR

2022-11-25 17:20 UTC, mnaser commented on images/capi/packer/qemu/packer.json
> +        "'-O'",
since this is unrelated to this, lets drop this from the PR

2022-11-28 09:55 UTC, drew-viles commented on docs/book/src/capi/providers/openstack-remote.md
> +
That's a good point actually. It's only really recommended by the builder docs for troubleshooting auth issues so I can get that removed. I'll try and get your points actioned today or tomorrow.

2022-11-28 09:55 UTC, drew-viles commented on docs/book/src/capi/providers/openstack-remote.md
> +> Other OS's will be supported at a later time.
Sounds good. We have no initial requirement right now but it would be good to see other distros supported.

2022-11-28 09:58 UTC, drew-viles commented on docs/book/src/capi/providers/openstack-remote.md
> +From the `images/capi` directory, run `PACKER_VAR_FILES=var_file.json make build-openstack-ubuntu-xxxx`.
Yeah no problem. Initially it was there because Ubuntu was the only one supported. When you get Flatcar in, if you want to change that too that would be great. For now I left it as Ubuntu as it's the only supported distro on this PR.

2022-11-28 09:58 UTC, drew-viles commented on docs/book/src/capi/providers/openstack-remote.md
> +An instance is built in Openstack from the source image defined and once completed, the instance is shutdown and the volume uploaded into an image that can then be used.
I'm happy with that change of wording - I'll take it in.

2022-11-28 10:01 UTC, drew-viles commented on images/capi/Makefile
> +#TODO    hack/ensure-openstack.sh
No it's not and I thought I had removed that comment to be honest. I'll get it removed.

2022-11-28 10:02 UTC, drew-viles commented on images/capi/packer/openstack/packer.json
> +    },
I can certainly test that to confirm it doesn't interfere and if so, I'll get it dropped. Anything to speed up the run is welcome.

2022-11-28 10:06 UTC, drew-viles commented
Thanks for the feedback @mnaser . As you can probably see this was a translation from the qemu setup so there will be some legacy bits hanging around from that.

I'll take your suggestions on board and run some tests to ensure it's still functioning as expected. All being well I'll get them committed into this PR so we can move forward.

I look forward to seeing more distros being added in so flatcar will be more than welcome.

2023-01-18 13:05 UTC, drew-viles commented
I'm going to add WIP whilst I add some additional features around metadata additions and review the PR for flatcar support.

2023-02-24 16:58 UTC, drew-viles commented on images/capi/packer/openstack/packer.json
> +    },
I've had to leave a subset of this in as without it we are seeing a failure to connect via SSH.

Happy to have this confirmed as not required with updated docs to match the change.

For now though, I've left it in as it's not causing any issues with it being there.

2023-02-24 17:00 UTC, drew-viles commented
@okozachenko1203 Could you authorise yourself as per the [comment above](https://github.com/kubernetes-sigs/image-builder/pull/1013#issuecomment-1443933202) please so we can put this in for review?

2023-03-09 11:57 UTC, drew-viles commented
@okozachenko1203 Polite bump RE comment above 😉

2023-03-15 12:50 UTC, okozachenko1203 commented
> @okozachenko1203 Please could you authorise yourself as per the [comment above](https://github.com/kubernetes-sigs/image-builder/pull/1013#issuecomment-1443933202)? Then we can put this in for review 🙌

@drew-viles I did it

2023-03-15 13:49 UTC, drew-viles commented
@codenrhoden, @mdbooth, @jsturtevant, @kkeshavamurthy

I think we're ready. Are you able to take a look when you get a bit of time?

Thanks!

2023-03-15 13:51 UTC, drew-viles commented
@codenrhoden, @mdbooth, @jsturtevant, @kkeshavamurthy

It looks like I removed you from reviewing by re-requesting @mnaser so retagging.

I think we're ready. Are any of you able to take a look when you get a bit of time?

Thanks!

2023-03-16 19:41 UTC, kkeshavamurthy commented on images/capi/ansible/roles/node/tasks/main.yml
> +    - { param: fs.inotify.max_user_watches, val: 524288 }
Can you provide a reason for making this change across all os & platforms?

2023-03-16 20:02 UTC, drew-viles commented on images/capi/ansible/roles/node/tasks/main.yml
> +    - { param: fs.inotify.max_user_watches, val: 524288 }
We did start to see some errors relating to "too many open files" and this change came off the back of that.

@yankcrime added this to resolve that problem, as for it being across all platforms he may be able to provide additional information here - I suspect it was to attempt to alleviate any pains others may see around this.

2023-03-17 05:51 UTC, yankcrime commented on images/capi/ansible/roles/node/tasks/main.yml
> +    - { param: fs.inotify.max_user_watches, val: 524288 }
The honest answer is that this was the quickest place for me to set these values when building our images ;)  However, as @drew-viles suggested it's really common to hit these limits and it often results in opaque errors to end-users so there's definitely an advantage to bumping the defaults globally.

However, I totally understand that this change is outside the proposed scope of this PR, so we can revert this commit if it's particularly contentious.

2023-03-20 15:26 UTC, mdbooth commented
I have submitted https://github.com/kubernetes-sigs/image-builder/pull/1117 to hopefully reduce the number of approvals required by this PR.

2023-03-20 16:15 UTC, mdbooth commented
> > /lgtm
> > With the exception of the issue highlighted by @kkeshavamurthy above this looks like an isolated feature which won't affect anybody not using it. There seem to be several groups of users asking for it, so I think we'll be best served by getting this merged so we can begin the process of battle-hardening it.
> > It looks like docs/OWNERS is a bit messed up. I might submit a PR to add at least cluster-api-maintainers to the owners of that directory.
> 
> @mdbooth / @kkeshavamurthy Do you want me to back that out then? We can make that an optional adjustment in a future PR if need be. We have seen it a couple of times now where that's needed doing on our clusters though which is why it was put in originally.

I think backing it out would make this PR entirely self-contained, so ideally yes. However, I don't have an opinion on the specific change myself, so if @kkeshavamurthy isn't going to object it might not be worth removing it.

2023-03-20 16:15 UTC, mdbooth commented
/lgtm

2023-03-20 17:47 UTC, kkeshavamurthy commented
@drew-viles please squash the commits and we'll get this PR merged.

2023-03-20 20:13 UTC, drew-viles commented
I certainly can. Leave it with me and I'll get that done asap.

Thanks!

2023-03-20 20:36 UTC, drew-viles commented
@mdbooth / @kkeshavamurthy 

All done.
Thanks again for taking the time on this! First PR into a project like this is always a learning curve!

2023-03-21 10:29 UTC, mdbooth commented
The commits aren't quite right. The second contains more than the requested change.

Just In Case(tm) (you may also know 3 better ways to achieve the same thing) you can fix this by doing the following:

* orighead=$(git rev-parse HEAD)
  * This stores the commit id of the current HEAD so we can re-use the commit message later.
* git reset HEAD^
  * This updates the current HEAD to be the commit before without changing anything in the working directory.
* git add docs/  images/capi/packer/openstack
  * This stages all the changes from your second commit *except* the kernel change
* git commit --amend
  * This updates the previous commit to contain the staged changes
* git commit -a -c $orighead
  * This commits all remaining changes (which is now just the kernel change) using the commit message from your original commit.
 
 Apologies if I'm teaching you to suck eggs!

2023-03-21 10:48 UTC, drew-viles commented
> The commits aren't quite right. The second contains more than the requested change.
> 
> Just In Case(tm) (you may also know 3 better ways to achieve the same thing) you can fix this by doing the following:
> 
> * orighead=$(git rev-parse HEAD)
>   
>   * This stores the commit id of the current HEAD so we can re-use the commit message later.
> * git reset HEAD^
>   
>   * This updates the current HEAD to be the commit before without changing anything in the working directory.
> * git add docs/  images/capi/packer/openstack
>   
>   * This stages all the changes from your second commit _except_ the kernel change
> * git commit --amend
>   
>   * This updates the previous commit to contain the staged changes
> * git commit -a -c $orighead
>   
>   * This commits all remaining changes (which is now just the kernel change) using the commit message from your original commit.
> 
> Apologies if I'm teaching you to suck eggs!

You're absolutely not! I think I know a lot about git then learn 5 new things a day :-D Let me get that sorted with your recommendation and I'll get it repushed.

2023-03-21 11:22 UTC, mdbooth commented
Perfect, thanks!

/lgtm

2023-03-21 11:34 UTC, mdbooth commented on images/capi/packer/openstack/OWNERS
> +  - cluster-api-openstack-maintainers
A suggestion, possibly for a new PR:

Create a new image-builder-openstack-maintainers alias containing yoursel(f|ves) to OWNERS_ALIASES, and add that alias to approvers here.

Incidentally, I wonder if @hidekazuna still wants to be a reviewer in this project? I suspect not.

2023-03-21 11:36 UTC, drew-viles commented on images/capi/packer/openstack/OWNERS
> +  - cluster-api-openstack-maintainers
That sounds like a good idea to me.
I do have a few more in the pipeline for this section of the project (could be useful globally too) from GPU support to other optional features so more PRs will come in soon once this one is in. I just wanted to get the basics down first.

Thanks for your help getting this across the line.

2023-03-22 15:26 UTC, jsturtevant commented
/lgtm
/assign @kkeshavamurthy @mboersma

2023-03-22 17:22 UTC, mboersma reviewed
This is great work! I just had some small doc comments.

2023-03-22 17:22 UTC, mboersma commented on docs/book/src/capi/providers/openstack-remote.md
> +The image is built using Openstack.
```suggestion
The image is built using OpenStack.
```

2023-03-22 17:22 UTC, mboersma commented on docs/book/src/capi/providers/openstack-remote.md
> +Also ensure you have a [Ubuntu 20.04](https://cloud-images.ubuntu.com/focal/current/) or [Ubuntu 22.04](https://cloud-images.ubuntu.com/jammy/current/) cloud image available in your Openstack instanc
```suggestion
Also ensure that you have a [Ubuntu 20.04](https://cloud-images.ubuntu.com/focal/current/) or [Ubuntu 22.04](https://cloud-images.ubuntu.com/jammy/current/) cloud image available in your OpenStack instance before continuing as it will need to be referenced.
```

2023-03-22 17:22 UTC, mboersma commented on docs/book/src/capi/providers/openstack-remote.md
> +This also supports Flatcar - so far only Stable has been tested.
```suggestion
This build process also supports Flatcar Linux, but only Stable has been tested.
```

2023-03-22 17:22 UTC, mboersma commented on docs/book/src/capi/providers/openstack-remote.md
> +> Other OS's could be supported and additions are welcome.
```suggestion
> Other operating systems could be supported and additions are welcome.
```

2023-03-22 17:22 UTC, mboersma commented on docs/book/src/capi/providers/openstack-remote.md
> +Ensure you have set up your method of authentication - [examples here](https://docs.openstack.org/python-openstackclient/zed/cli/authentication.html).
```suggestion
Ensure you have set up your method of authentication. See the [examples here](https://docs.openstack.org/python-openstackclient/zed/cli/authentication.html).
```

2023-03-22 17:22 UTC, mboersma commented on docs/book/src/capi/providers/openstack-remote.md
> +You should be able to run commands against openstack before running this builder otherwise it will fail.
```suggestion
You should be able to run commands against OpenStack before running this builder, otherwise it will fail.
```

2023-03-22 17:22 UTC, mboersma commented on docs/book/src/capi/providers/openstack-remote.md
> +building Openstack images are managed by running:
```suggestion
building OpenStack images are managed by running:
```

2023-03-22 17:22 UTC, mboersma commented on docs/book/src/capi/providers/openstack-remote.md
> +### Define variables for Openstack build
```suggestion
### Define variables for OpenStack build
```

2023-03-22 17:22 UTC, mboersma commented on docs/book/src/capi/providers/openstack-remote.md
> +A certain set of environment variables (example below) must be defined in a json file and referenced as shown below in the build example.
```suggestion
A certain set of environment variables must be defined in a json file and referenced as shown below in the build example.
```

2023-03-22 17:22 UTC, mboersma commented on docs/book/src/capi/providers/openstack-remote.md
> +### Building Image on Openstack
```suggestion
### Building Image on OpenStack
```

2023-03-22 17:22 UTC, mboersma commented on docs/book/src/capi/providers/openstack-remote.md
> +For building a ubuntu-2204 based capi image with Kubernetes 1.23.15, run the following commands:
```suggestion
For building a ubuntu 22.04-based CAPI image with Kubernetes 1.23.15, run the following commands:
```

2023-03-22 21:25 UTC, drew-viles commented on images/capi/packer/openstack/OWNERS
> +  - cluster-api-openstack-maintainers
Since I'm putting the docs suggested in by @mboersma , I'll also get this put in now as it makes sense to add this anyway. Once in I'll resolve this and tag (hopefully) one last time for a review.

2023-03-22 21:41 UTC, drew-viles commented
Thanks @mboersma. All very logical updates :-) 
I've committed them into the first commit just now. We wanted to keep it with just two commits as suggested by @kkeshavamurthy so that there was one for the OpenStack additions and one for the kernel adjustments.

So, I hope we're good to go now :-) Let me know if anything else is needed before we go forward with this.

I'll tag people again so we can get the final lgtm and approvals.

@mdbooth 
@jsturtevant

2023-03-23 15:42 UTC, mboersma reviewed
/lgtm

2023-03-23 19:00 UTC, kkeshavamurthy commented
/lgtm
/approve

Thanks for the patience and working thru all the reviews @drew-viles . Congrats on the first PR to this repo :). Hope to see more in the future :)

2023-03-23 19:02 UTC, merged