Add chrony hook for Openstack
kubernetes-sigs/image-builder pull request #1225
Opened 2023-07-12 08:57 UTC by mpiscaer

Add the networkd-dispatcher for chrony, this will make sure that Openstack images, check for the DNS srv record and DHCP option 42.

What this PR does / why we need it:

The current Openstack images do not install the NTP servers in chrony when DHCP option 42 set or the _ntp._udp DNS SRV records are there. To fix this the networkd-dispatcher is needed.

2023-07-12 23:00 UTC, mnaser commented
@mpiscaer : this is good on the surface but if you want to resolve this for the images we use in the Cluster API, it would be best to make the change in the `qemu` section, since that is what we use there.

Also, it would be good to introduce GOSS tests for the both OpenStack and QEMU:

https://github.com/kubernetes-sigs/image-builder/blob/main/images/capi/packer/goss/goss-vars.yaml#L204-L207C22

I think you'd be able to slot it in here for Ubuntu both for QEMU and OpenStack:

2023-07-12 23:00 UTC, mnaser requested changes
needs some goss tests + would be nice to add to the `qemu` image.

2023-07-13 02:07 UTC, mnaser commented
/ok-to-test

2023-07-13 06:06 UTC, AverageMarcus commented
/lgtm

@mpiscaer Could you please [squash your commits](https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md#squash-commits)?

2023-07-13 13:45 UTC, AverageMarcus commented
/test pull-azure-vhds

2023-07-13 14:16 UTC, AverageMarcus commented
/lgtm
/approve

2023-07-13 14:18 UTC, merged