Ansible actions use fully-qualified collection names
kubernetes-sigs/image-builder pull request #1404
Opened 2024-02-13 15:10 UTC by jongwooo

## Change description

Use [fully-qualified collection name](https://ansible.readthedocs.io/projects/lint/rules/fqcn) of all ansible actions.

**AS-IS**

```yaml
win_firewall_rule:
```

**TO-BE**

```yaml
community.windows.win_firewall_rule:
```

/cc @mboersma @AverageMarcus 

## Related issues

- Fixes #1312 

## Additional context

None

2024-02-13 18:00 UTC, mboersma commented
/ok-to-test

2024-02-13 18:31 UTC, mboersma commented on images/capi/ansible/roles/sysprep/tasks/redhat.yml
> -
It seems like `ansible-lint fix` removed some blank lines and this comment. I don't think the missing blank lines will cause a problem in YAML (although it would be better to keep them), but the comments are informative.

I'll go through this PR and identify where blank lines were removed and make sure there aren't any other omissions.

2024-02-22 19:03 UTC, mboersma requested changes
I'm sorry it took me so long to get back to this @jongwooo. I think I found all the places the linter removed comments or whitespace.

Hopefully you can make these changes and rebase the PR--I know it's huge and kind of tricky. Please let us know if you have any questions or need a hand.

2024-02-22 19:03 UTC, mboersma commented on images/capi/ansible/windows/roles/systemprep/tasks/main.yml
> +  ansible.windows.win_shell: If (-Not (Test-Path -Path "$env:ProgramData\ssh")) { mkdir "$env:ProgramData\ssh" }
```suggestion
  ansible.windows.win_shell: If (-Not (Test-Path -Path "$env:ProgramData\ssh")) { mkdir "$env:ProgramData\ssh" }

```
Restore blank line.

2024-02-22 19:03 UTC, mboersma commented on images/capi/ansible/windows/roles/systemprep/tasks/main.yml
> +  ansible.windows.win_shell: Add-Content -Path "$env:ProgramData\ssh\sshd_config" -Value "PasswordAuthentication no`nPubkeyAuthentication yes"
```suggestion
  ansible.windows.win_shell: Add-Content -Path "$env:ProgramData\ssh\sshd_config" -Value "PasswordAuthentication no`nPubkeyAuthentication yes"

```
Restore blank line.

2024-02-22 19:03 UTC, mboersma commented on images/capi/ansible/windows/roles/systemprep/tasks/main.yml
> +  ansible.windows.win_shell: netsh int ipv4 set dynamicportrange tcp 34000 31536
```suggestion
  ansible.windows.win_shell: netsh int ipv4 set dynamicportrange tcp 34000 31536

```
Restore blank line.

2024-02-22 19:03 UTC, mboersma commented on images/capi/ansible/windows/roles/systemprep/tasks/ssh-archive.yml
>      & 'C:\Program Files\OpenSSH\install-sshd.ps1'
```suggestion
    & 'C:\Program Files\OpenSSH\install-sshd.ps1'

```
Restore blank line.

2024-02-23 16:03 UTC, mboersma approved these changes
/lgtm

Thanks again for this! It looks good to me, but it's huge so let's have another maintainer take a look before we merge it.

/assign @AverageMarcus @drew-viles

2024-02-26 08:27 UTC, AverageMarcus reviewed
As best as I can tell this looks good. I haven't checked every single command is referencing the correct full name though but I trust that it's all correct. 😄 

/lgtm
/approve

2024-02-26 08:32 UTC, merged