Update containerd to 1.4.0
kubernetes-sigs/image-builder pull request #372
Opened 2020-09-11 20:00 UTC by ZihanJiang96

The containerd is released & packaged in a new way here: https://github.com/containerd/containerd/releases/tag/v1.4.0

After we download the tar.gz, configure the ansible role to remove /etc/cni and /opt/cni, as we will install cni later.

Corresponding issue https://github.com/kubernetes-sigs/image-builder/issues/332 @EleanorRigby

2020-09-11 20:27 UTC, ZihanJiang96 commented
I signed it

2020-09-11 20:43 UTC, ZihanJiang96 commented
I signed it.

2020-09-11 20:44 UTC, ZihanJiang96 commented
/assign @justinsb

2020-09-11 23:24 UTC, dims commented
/ok-to-test

Have you tested the generated image @ZihanJiang96 ?

2020-09-11 23:28 UTC, ZihanJiang96 commented
> /ok-to-test
> 
> Have you tested the generated image @ZihanJiang96 ?

tested on capv

2020-09-14 17:13 UTC, EleanorRigby requested changes

2020-09-14 17:13 UTC, EleanorRigby commented on images/capi/ansible/roles/containerd/tasks/main.yml
>  - name: Creates unit file directory
Should we remove this? As 1.4 tar unpack will install systemd unit file

2020-09-14 17:51 UTC, ZihanJiang96 commented on images/capi/ansible/roles/containerd/tasks/main.yml
>  - name: Creates unit file directory
The 1.4 tar includes **containerd.service** with
[Service]
Type=notify

2020-09-14 17:55 UTC, ZihanJiang96 commented on images/capi/ansible/roles/containerd/tasks/main.yml
>  - name: Creates unit file directory
And the 1.4 tar also contains the file **10-containerd-net.conflist** under **/etc/cni/net.d/**. We don't have to use this default cni config that is included. Later we will install CNI, plugins, and config separately.

2020-09-14 21:18 UTC, EleanorRigby commented on images/capi/ansible/roles/containerd/tasks/main.yml
>  - name: Creates unit file directory
@ZihanJiang96 : I think I was not clear. I am talking about code line # 55  `- name: Creates unit file directory`. Shouldn't unpack create this directory? We can remove this task.

2020-09-14 21:24 UTC, EleanorRigby commented
/assign

2020-09-14 21:36 UTC, ZihanJiang96 commented on images/capi/ansible/roles/containerd/tasks/main.yml
>  - name: Creates unit file directory
@EleanorRigby the tar doesn't have this dir:
```
➜  cri-containerd-cni-1.4.0-linux-amd64 tree
.
├── etc
│   ├── cni
│   │   └── net.d
│   │       └── 10-containerd-net.conflist
│   ├── crictl.yaml
│   └── systemd
│       └── system
│           └── containerd.service
```

2020-09-14 23:38 UTC, EleanorRigby commented on images/capi/ansible/roles/containerd/tasks/main.yml
>  - name: Creates unit file directory
Understood.

2020-09-14 23:40 UTC, EleanorRigby commented
@ZihanJiang96 : Mostly, this looks good to me. I will give it a run locally for final verification before lgtm.

2020-09-17 20:00 UTC, closed without merging