Add auditd for Ubuntu
kubernetes-sigs/image-builder pull request #373
Opened 2020-09-14 18:46 UTC by SanikaGawhane

Add audit logs for Ubuntu.

2020-09-14 21:23 UTC, EleanorRigby requested changes
All current changes LGTM.
It will be a good idea to also change `goss/goss-vars.yaml` to account for the audit package in Debian based OS.

2020-09-14 21:24 UTC, EleanorRigby commented
/assign

2020-09-14 22:44 UTC, EleanorRigby requested changes

2020-09-14 22:44 UTC, EleanorRigby commented on images/capi/packer/goss/goss-vars.yaml
> +  auditd:
Since it is common to all Debian/rpm/photon OS, let's remove it entirely from here and put it in `goss-package.yaml`.  Check line#43, #169 for more presence of audit in this file. 

Please give it a run to check if GOSS passes. Editing variable files can sometimes have undesired effects on `goss render` and hence, `goss validate` too.

2020-09-15 19:33 UTC, SanikaGawhane commented on images/capi/packer/goss/goss-vars.yaml
> +  auditd:
The names used for audit package vary - `rpms` uses `audit` whereas `debs` uses `auditd`. It will be a complex conditional statement to specify each case in `goss-package.yaml`. Hence leaving it here.

2020-09-18 15:31 UTC, EleanorRigby commented
/ok-to-test

Verified locally. Audit rules exist. Log directory was recreated and logs were present.

2020-09-18 15:32 UTC, EleanorRigby commented
Will wait for the test to finish once for lgtm

2020-09-18 16:32 UTC, EleanorRigby commented
/lgtm

2020-09-18 17:04 UTC, frapposelli commented
/approve

2020-09-18 17:11 UTC, ncdc commented
/approve

2020-09-18 17:12 UTC, merged