WIP: Add chrony module for supported distros and providers
kubernetes-sigs/image-builder pull request #397
Opened 2020-10-05 17:57 UTC by SanikaGawhane

Use `chrony` time sync service in -
- AMIs
- VHDs
- OVAs

2020-10-05 18:08 UTC, EleanorRigby requested changes

2020-10-05 18:08 UTC, EleanorRigby commented on images/capi/ansible/roles/providers/tasks/aws.yml
> +- name: Ansible yum install chrony
Should this be done when `when: ansible_os_family != "Debian"`

If there are too many ops like this, you can create files like `redhat.yml` `debian.yml` to reference them with a conditional.

2020-10-05 18:08 UTC, EleanorRigby commented on images/capi/ansible/roles/providers/tasks/aws.yml
> +    daemon_reload: yes
What is `daemon_reload` for?

2020-10-05 18:08 UTC, EleanorRigby commented on images/capi/ansible/roles/providers/tasks/azure.yml
> +  yum:
Ubuntu and yum mistake. Need more conditionals to restrict this to centos like OSs

2020-10-05 18:08 UTC, EleanorRigby commented on images/capi/ansible/roles/providers/tasks/vmware.yml
> +  yum:
Needs correction. Can run for Debian system also.

2020-10-05 18:08 UTC, EleanorRigby commented
/assign

2020-10-06 22:10 UTC, SanikaGawhane commented on images/capi/ansible/roles/providers/tasks/azure.yml
> +  yum:
Ansible has a generic package installation manager that uses yum/apt depending on which system (RPM/Debian) the package is being installed - https://docs.ansible.com/ansible/2.5/modules/package_module.html

2020-10-06 22:19 UTC, SanikaGawhane commented on images/capi/ansible/roles/providers/tasks/aws.yml
> +    daemon_reload: yes
Reloads systemd manager configuration. It is kind of a soft reload that reruns all generators, takes changed configurations from filesystem and regenerates dependency trees. We use it in `containerd` too - https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/ansible/roles/containerd/tasks/main.yml#L92

2020-10-07 16:31 UTC, EleanorRigby commented
Is this still a work in progress?

2020-10-07 16:38 UTC, EleanorRigby commented on images/capi/ansible/roles/providers/tasks/vmware.yml
> +- name: Ansible install chrony
I am wondering if we should add chrony to the base package list? 

and individual configs can remain in provider like `Ensure makestep parameter set as ..` can stay in azure provider.

Is it mandatory to remove `ntp` first? Or the ops to add chrony and delete ntpd are mutually exclusive? If they are muttually exclusive then it is  good to move it to base package list in role `node`

2020-10-07 16:38 UTC, EleanorRigby commented on images/capi/ansible/roles/providers/tasks/aws.yml
> +    name: ntp*
Can we be specific about which packages to remove? Is it because ntp has different package names in different OSs?

2020-10-07 16:38 UTC, EleanorRigby commented
/ok-to-test

2020-10-07 17:53 UTC, kkeshavamurthy commented on images/capi/ansible/roles/providers/tasks/aws.yml
> +    name: ntp*
Are we removing it explicitly because it's built in or can we just remove it from the pkg list?

2020-10-07 18:40 UTC, SanikaGawhane commented on images/capi/ansible/roles/providers/tasks/aws.yml
> +    name: ntp*
@EleanorRigby - Correct, the package can have names `ntp` or `ntpd` depending on the system.

@kkeshavamurthy - Right, we remove it because it is built in and my guess is it might default to `ntpd` if it is present. AWS recommends this [step](https://aws.amazon.com/blogs/aws/keeping-time-with-amazon-time-sync-service/).

2020-10-07 18:40 UTC, SanikaGawhane commented on images/capi/ansible/roles/providers/tasks/vmware.yml
> +- name: Ansible install chrony
Adding chrony to the base package list is a good idea and make the configs cleaner. 

`ntpd` and `chrony` can both be installed and kept switching as needed. However, modern Fedora, CentOS, and RHEL releases have moved from NTP to Chrony as their default time-keeping implementation. That said, these are mutually exclusive and we can safely move `chrony` installation to base package list.

2020-10-12 17:44 UTC, EleanorRigby reviewed
/lgtm

2020-10-13 05:47 UTC, moshloop commented
Can we add some goss tests for this?

2020-10-28 20:46 UTC, SanikaGawhane commented
/assign @codenrhoden

2020-10-28 21:23 UTC, EleanorRigby requested changes
just a minor GOSS change. The rest looks good.

2020-10-28 21:23 UTC, EleanorRigby commented on images/capi/packer/goss/goss-package.yaml
> +  ntp:
This should not be under the above if. It is general and does not concern k8s source type.

2020-11-04 21:07 UTC, detiber commented on images/capi/ansible/roles/providers/tasks/aws.yml
> +- name: Ensure chrony is running
It seems odd to replicate this across all the different included providers, especially if we are handling the package installation more generally

2020-11-05 05:34 UTC, SanikaGawhane commented on images/capi/ansible/roles/providers/tasks/aws.yml
> +- name: Ensure chrony is running
Moved this check to `main.yml`

2020-11-05 07:03 UTC, EleanorRigby approved these changes
/lgtm

The only thing I noticed is that we left QEMU builder out for chrony changes. We can further investigate and introduce support in separate PR. This looks good for now.

2020-11-17 16:20 UTC, codenrhoden commented
/approve

I do wonder if there is any extra default configuration that can/should go in for other cloud providers (namely AWS). We have Azure's recommended config put in, but does AWS have anything similar?

Nice work @SanikaGawhane !

2020-11-17 16:52 UTC, merged