Adding CI for OVAs
kubernetes-sigs/image-builder pull request #425
Opened 2020-11-04 19:53 UTC by kkeshavamurthy

Created a new CI target to build all platforms except RHEL
Added CI script. 

CC: @codenrhoden

2020-11-04 20:03 UTC, EleanorRigby requested changes
Minor questions + change

2020-11-04 20:03 UTC, EleanorRigby commented on images/capi/packer/ova/scripts/ci-ova.sh
> +cat << EOF > vmc.json
If we just edit vsphere.json , can we use the same targets to trigger this?

Any reason to create vmc.json

2020-11-04 20:03 UTC, EleanorRigby commented on images/capi/Makefile
> +	packer build $(PACKER_NODE_FLAGS) -var-file="packer/ova/packer-common.json" -var-file="$(abspath packer/ova/$(subst build-node-ova-vsphere-,,$@).json)" -var-file="packer/ova/vsphere.json" -except=es
should this(packer/ova/vsphere.json) be vmc.json?

2020-11-04 20:21 UTC, EleanorRigby approved these changes
Looks good to me. will wait for one more review by someone who is familiar with CI

/lgtm

2020-11-04 20:21 UTC, EleanorRigby commented
/ok-to-test

2020-11-24 18:29 UTC, kkeshavamurthy commented
ping @codenrhoden

2021-01-04 20:09 UTC, kkeshavamurthy commented
/retest

2021-01-04 20:24 UTC, kkeshavamurthy commented
/test help

2021-01-04 20:25 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-01-04 21:42 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-01-04 21:47 UTC, kkeshavamurthy commented
@codenrhoden can you please help in creating this folder on the VMC Cluster

```
Build 'vsphere' errored: error creating vm: folder '/SDDC-Datacenter/vm/imagebuilder' not found
```

2021-01-04 22:02 UTC, codenrhoden commented
@kkeshavamurthy yes, I was able to create a folder for you.

Try setting the folder to `/SDDC-Datacenter/vm/Workloads/ci/imagebuilder`

2021-01-04 23:14 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-01-04 23:32 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-01-04 23:41 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-01-07 19:38 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-01-07 19:51 UTC, codenrhoden commented
/test pull-ova-all

2021-01-07 19:58 UTC, codenrhoden commented
/test pull-ova-all

2021-01-07 21:05 UTC, codenrhoden commented
/test pull-ova-all

2021-01-07 21:10 UTC, codenrhoden commented
/test pull-ova-all

2021-01-07 21:13 UTC, codenrhoden commented
/test pull-ova-all

2021-01-07 21:21 UTC, codenrhoden commented
/test pull-ova-all

2021-01-07 21:36 UTC, codenrhoden commented
@kkeshavamurthy okay, some progress! It did try to create the VM. It's failing at loading the kickstart file because I don't think it has the right IP address. IN the VM console, it's trying to reach the Packer HTTP server at 10.60.115.27, which does not look like it's through the VPN to me.

If it was through the VPN, it would be looking on a **10.8.0.x** address.

I think the next actions here are:

- Get you a VMC account so you can see the VM consoles for debugging (there will probably be  more issues)
- Figure out how to get Packer to bind to the VPN address instead. Maybe there is an openvpn command that you can use to get the IP address, then use it to configure Packer with https://www.packer.io/docs/builders/vmware/vsphere-iso#http_bind_address.

2021-01-07 21:37 UTC, codenrhoden commented
I'm also going to let this job keep running for now (it's stuck) to see what the behavior is.

2021-01-09 00:15 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-01-09 00:19 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-01-09 00:25 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-01-09 00:55 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-01-11 16:40 UTC, codenrhoden commented on images/capi/packer/ova/packer-node.json
> +      "vm_name": "{{user `build_version`}}-{{user `build_timestamp`}}",
A couple things come to mine here... When we added the `vsphere-iso` builder, it originally had `-force` in the `packer build` command to prevent the error you are seeing with the VM already existing. I didn't like that idea because an errant `make` could quickly/easily destroy an existing build that may be in use as a template.

For CI, it may be appropriate to set `PACKER_FLAGS=-force` (I think that's what it would be). I think setting the VM name differently may have other effects, but now that I look through `packer-node.json` it doesn't appear to be used or passed on to the OVA scripts, so maybe it is safe. :)

Regardless, if you want to do this, I think it needs to go in `vsphere-iso` builder, not `vmware-iso`.

2021-01-11 16:40 UTC, codenrhoden commented on images/capi/Makefile
> +build-node-ova-vsphere-ci-all: $(NODE_OVA_VSPHERE_CI_BUILD_TARGETS) ## Builds all Node OVAs and templates on vSphere except RHEL
Rather than adding additional make targets, I think I'd prefer to just keep the new `test-ova` target that calls the `ci-ova.sh` script, and control which targets are called in the script.

Meaning that in the script, we would do something like
```sh
make -j build-node-ova-vsphere-photon-3 build-node-ova-vsphere-ubuntu-2004 build-node-ova-vsphere-ubuntu-1804 build-node-ova-vsphere-centos-7
```

That way we just use the existing targets rather than creating special "CI" targets. Thoughts?

2021-01-11 17:51 UTC, kkeshavamurthy commented on images/capi/packer/ova/packer-node.json
> +      "vm_name": "{{user `build_version`}}-{{user `build_timestamp`}}",
I meant to put it in `vsphere-iso`. Thanks for catching that. 
Yeah I looked thru the code and did not see the vm name being anywhere else so went this route. I prefer this method instead of force
from packer doc:
`  -force                        Force a build to continue if artifacts exist, deletes existing artifacts.`
So this means packer might destroy the vm that's started by another ci run?

2021-01-11 17:52 UTC, kkeshavamurthy commented on images/capi/Makefile
> +build-node-ova-vsphere-ci-all: $(NODE_OVA_VSPHERE_CI_BUILD_TARGETS) ## Builds all Node OVAs and templates on vSphere except RHEL
This works. Will change it.

2021-01-11 18:53 UTC, codenrhoden commented on images/capi/packer/ova/packer-node.json
> +      "vm_name": "{{user `build_version`}}-{{user `build_timestamp`}}",
Yeah, I agree. Since it't not being used anywhere else, seems safe.  In the job definition, we have this set:
https://github.com/kubernetes/test-infra/blob/5d64d2ba2ac533041f2328e0eaf4519799f38336/config/jobs/kubernetes-sigs/image-builder/image-builder-ova-presubmits.yaml#L13
So yeah, we can have concurrent builds. Which means that if we didn't do this, they would overwrite each other. :)

2021-01-11 23:15 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-01-12 00:41 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-01-12 00:46 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-01-12 01:09 UTC, kkeshavamurthy commented
@codenrhoden I think I'm running into this [issue](https://github.com/hashicorp/packer/issues/9973#issuecomment-728917359) 

`http_bind_address` sets the bind address correctly for packer but the boot line command issued is with the non-vpn IP which packer picks by default. There's a [PR](https://github.com/hashicorp/packer/pull/10273) open for the fix. 
Until then any idea for getting around the issue?

```
 ==> vsphere: File already uploaded; continuing
==> vsphere: Creating VM...
==> vsphere: Customizing hardware...
==> vsphere: Mounting ISO images...
2021/01/12 00:49:13 packer-builder-vsphere-iso plugin: Creating CD-ROM on controller '&{{{} 200 0xc00027af00 <nil> <nil> <nil> 0 <nil>} 0 []}' with iso '[WorkloadDatastore] packer_cache//d3e175624fc2d704975ce9a149f8f270e4768727.iso'
2021/01/12 00:49:13 packer-builder-vsphere-iso plugin: No floppy files specified. Floppy disk will not be made.
2021/01/12 00:49:13 packer-builder-vsphere-iso plugin: Found available port: 8286 on IP: 10.8.0.6
==> vsphere: Starting HTTP server on port 8286
==> vsphere: Set boot order temporary...
==> vsphere: Power on VM...
==> vsphere: Waiting 10s for boot...
==> vsphere: HTTP server is working at http://10.60.104.135:8286/
==> vsphere: Typing boot command...
2021/01/12 00:49:24 packer-builder-vsphere-iso plugin: Special code '<esc>' found, replacing with: CodeEscape
2021/01/12 00:49:24 packer-builder-vsphere-iso plugin: Waiting 1 second
2021/01/12 00:49:45 packer-builder-vsphere-iso plugin: Special code '<enter>' found, replacing with: CodeReturnEnter
2021/01/12 00:49:45 packer-builder-vsphere-iso plugin: Waiting 1 second
2021/01/12 00:49:46 packer-builder-vsphere-iso plugin: [INFO] Waiting for IP, up to total timeout: 30m0s, settle timeout: 5s
==> vsphere: Waiting for IP... 
```

2021-02-10 00:00 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-02-10 01:49 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-02-10 03:24 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-02-10 06:49 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-03-08 21:44 UTC, codenrhoden commented
/test pull-ova-all

2021-03-08 22:23 UTC, codenrhoden commented
/test pull-ova-all

2021-03-09 16:05 UTC, codenrhoden commented
/test pull-ova-all

2021-03-09 16:50 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-04-19 22:52 UTC, codenrhoden commented
While I kind of hate the idea, one way to maybe get this unstuck is to take export and post-processing out with `jq` until we come up with a solution. Maybe something like:

```
jq 'del(.builders[].export)' | jq 'del(."post-processors")'
```

For example, if I do a diff on before/after that command, it seems to only take out the needed stuff:

```sh
$ diff <(cat packer-node.json) <(cat packer-node.json | jq 'del(.builders[].export)' | jq 'del(."post-processors")')
139,142d138
<       "export": {
<         "force": true,
<         "output_directory": "{{user `base_output_dir`}}"
<       },
192,196d187
<       "export": {
<         "force": true,
<         "manifest": "{{ user `export_manifest`}}",
<         "output_directory": "{{user `output_dir`}}"
<       },
239,243d229
<       "export": {
<         "force": true,
<         "manifest": "{{ user `export_manifest`}}",
<         "output_directory": "{{user `output_dir`}}"
<       },
262,331d247
<   "post-processors": [
<     {
<       "custom_data": {
<         "build_date": "{{isotime}}",
<         "build_name": "{{user `build_name`}}",
<         "build_timestamp": "{{user `build_timestamp`}}",
<         "build_type": "node",
<         "containerd_version": "{{user `containerd_version`}}",
<         "custom_role": "{{user `custom_role`}}",
<         "disk_size": "{{user `disk_size`}}",
<         "distro_arch": "{{ user `distro_arch` }}",
<         "distro_name": "{{ user `distro_name` }}",
<         "distro_version": "{{ user `distro_version` }}",
<         "guest_os_type": "{{user `guest_os_type`}}",
<         "ib_version": "{{user `ib_version`}}",
<         "kubernetes_cni_semver": "{{user `kubernetes_cni_semver`}}",
<         "kubernetes_semver": "{{user `kubernetes_semver`}}",
<         "kubernetes_source_type": "{{user `kubernetes_source_type`}}",
<         "kubernetes_typed_version": "{{user `kubernetes_typed_version`}}",
<         "os_name": "{{user `os_display_name`}}",
<         "vsphere_guest_os_type": "{{user `vsphere_guest_os_type`}}"
<       },
<       "except": [
<         "vmware-iso-base"
<       ],
<       "output": "{{user `output_dir`}}/packer-manifest.json",
<       "strip_path": true,
<       "type": "manifest"
<     },
<     {
<       "inline": [
<         "cd {{user `output_dir`}}",
<         "tar xf {{user `build_version`}}.ova",
<         "rm {{user `build_version`}}.ova",
<         "../../hack/image-build-ova.py --stream_vmdk --node --vmx {{user `vmx_version`}} --eula ../../hack/ovf_eula.txt --ovf_template ../../hack/ovf_template.xml --vmdk_file {{user `build_version`}}-disk1.vmdk"
<       ],
<       "name": "esx",
<       "type": "shell-local"
<     },
<     {
<       "inline": [
<         "cd {{user `output_dir`}}",
<         "../../hack/image-build-ova.py --node --vmx {{user `vmx_version`}} --eula ../../hack/ovf_eula.txt --ovf_template ../../hack/ovf_template.xml --vmdk_file {{user `build_version`}}-disk-0.vmdk"
<       ],
<       "name": "vsphere",
<       "type": "shell-local"
<     },
<     {
<       "except": [
<         "vmware-iso-base"
<       ],
<       "inline": [
<         "./hack/image-build-ova.py --stream_vmdk --node --vmx {{user `vmx_version`}} --eula ./hack/ovf_eula.txt --ovf_template ./hack/ovf_template.xml {{user `output_dir`}}",
<         "./hack/image-post-create-config.sh {{user `output_dir`}}"
<       ],
<       "name": "local",
<       "type": "shell-local"
<     },
<     {
<       "environment_vars": [
<         "CUSTOM_POST_PROCESSOR={{user `custom_post_processor`}}"
<       ],
<       "inline": [
<         "if [ \"$CUSTOM_POST_PROCESSOR\" != \"true\" ]; then exit 0; fi",
<         "{{user `custom_post_processor_command`}}"
<       ],
<       "name": "custom-post-processor",
<       "type": "shell-local"
<     }
<   ],
```

2021-04-19 22:57 UTC, codenrhoden commented
I feel like the long-term solution is to just create the working template in vCenter and leave it there (no export), but that means we will want to set fields in a template's vApp properties... I'm not sure what the best way to do that right now is, but it might be with `govc`. Either with a CLI (short-term) or by embedding into a a CLI (meaning I'm using this as an argument in favor of it).

2021-07-08 08:11 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-07-08 16:17 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-07-08 16:26 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-07-08 16:36 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-07-08 16:41 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-07-09 06:51 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-07-09 10:41 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-07-09 14:22 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-07-09 14:28 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-07-09 14:34 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-07-09 14:45 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-07-09 14:49 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-07-09 15:09 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-07-09 16:13 UTC, codenrhoden commented
/test pull-goss-populate
^ this seemed like an environment flake. It wouldn't even normally need to run for this PR, but I'd like to see if it passes now.

2021-07-09 16:24 UTC, kkeshavamurthy commented
/test pull-azure-vhds

2021-07-09 16:37 UTC, kkeshavamurthy commented
/test pull-ova-all

2021-07-09 16:58 UTC, codenrhoden commented
/lgtm
/approve

Nice work @kkeshavamurthy. You're persistence and hard work paid off! :)

2021-07-09 17:14 UTC, kkeshavamurthy commented
/test pull-azure-all

2021-07-09 17:14 UTC, kkeshavamurthy commented
/test pull-azure-vhds

2021-07-09 17:42 UTC, merged