capi: make containerd CRI socket configurable
kubernetes-sigs/image-builder pull request #433
Opened 2020-11-18 14:25 UTC by dongsupark

We should be able to configure path to containerd CRI socket file, `containerd_cri_socket`, for each distro.
Its main use case is to support distros with different CRI socket path, for example, `/run/docker/libcontainerd/container.sock` for Flatcar.
By default it is `/var/run/containerd/containerd.sock` as it has been in all other distros.

This PR is split out from https://github.com/kubernetes-sigs/image-builder/pull/248, as suggested by @codenrhoden.

2020-11-18 14:27 UTC, dongsupark commented
/assign @ncdc

2020-11-18 21:46 UTC, codenrhoden requested changes
/ok-to-test

Thanks for breaking this out, @dongsupark.

I have one request. Rather than putting `containerd_cri_socket` into every other OS, let's instead put it in `config/containerd.json`. Since the existing value of `/var/run/containerd/containerd.sock` is indeed a default for all current OS's, there's no need to define it each place.

looking forward to flatcar support, you can then override this value in *only* your `flatcar.json` file. The makefile ensures that the OS-specific JSON file is loaded after all the "defaults" that are in the `config` folder, which for Packer means the OS-specific JSON files take precedence.

/assign @moshloop 
^ Moshe, I know you wanted to see this happen separately as well.

2020-11-19 10:54 UTC, dongsupark commented
@codenrhoden Done.
Now `containerd_cri_socket` is defined only in `packer/config/containerd.json`.

2020-11-19 15:48 UTC, ncdc commented
@fabriziopandini this is probably worth your 👀 too - thanks

2020-11-19 16:53 UTC, codenrhoden commented
/lgtm

Will wait for others to chime in.

2020-11-30 20:12 UTC, detiber commented on images/capi/ansible/roles/containerd/templates/etc/crictl.yaml
> +runtime-endpoint: unix://{{ containerd_cri_socket }}
Should there also be a related change to one of the task files in `images/capi/ansible/roles/containerd/tasks` to reference this file?

2020-12-01 14:43 UTC, dongsupark commented on images/capi/ansible/roles/containerd/templates/etc/crictl.yaml
> +runtime-endpoint: unix://{{ containerd_cri_socket }}
> Should there also be a related change to one of the task files in images/capi/ansible/roles/containerd/tasks to reference this file?

Good catch. Thanks.
I forgot about moving the corresponding changes from https://github.com/kubernetes-sigs/image-builder/pull/248, when splitting out the PR.
Updated this PR.

2020-12-01 17:02 UTC, detiber reviewed
/lgtm

2020-12-03 15:48 UTC, codenrhoden commented
/approve

Thanks for the assist @detiber

2020-12-03 16:19 UTC, merged