Add image-promotion process to publish container images
kubernetes-sigs/image-builder pull request #450
Opened 2020-12-08 23:11 UTC by SanikaGawhane

Use GCR to publish official container images for image-builder. 

This PR

- Edits `Makefile` to build and push container image to the staging registry.
- Adds `cloudbuild.yaml` to produce a container image

2020-12-09 21:04 UTC, codenrhoden reviewed
/ok-to-test

2020-12-09 21:04 UTC, codenrhoden commented on images/capi/cloudbuild.yaml
> +      - PULL_BASE_REF=$_PULL_BASE_REF
After thinking about this a bit more, I think we can make our approach even simpler. I know we were taking this from CAPA, and if you look in their `MAKEFILE`, it is accepting these two vars. Our Makefile is only looking for `TAG`, but not `PULL_BASE_REF`. I also don't think we need either.

Our makefile dynamically determines the version by setting the `IB_VERSION` variable. I'd rather just continue to use that. Looking at it more, I'd rather see the Makefile not use `TAG` at all -- it should just be using `IB_VERSION`, but let's set that aside for now.

If my above comment is true (that we don't need the `DOCKER_CLI_...` var) I think we can remove the entire `env:` section, the `substitution:` section, and probably the `options:` section too? What do you think?

The way you've said up the Makefile target is perfect - a raw call to `make release-staging` should just do the right thing, no extra env vars needed.

2020-12-09 23:14 UTC, CecileRobertMichon commented on images/capi/cloudbuild.yaml
> +      - DOCKER_CLI_EXPERIMENTAL=enabled
you can use this [PR](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1061/files) as an example of leveraging docker build kit to build images

2020-12-09 23:15 UTC, CecileRobertMichon commented on images/capi/cloudbuild.yaml
> +      - PULL_BASE_REF=$_PULL_BASE_REF
CAPA isn't doing the latest in terms of image building. I'd recommend looking at CAPI or CAPZ.

2020-12-11 19:40 UTC, codenrhoden commented on images/capi/cloudbuild.yaml
> +      - PULL_BASE_REF=$_PULL_BASE_REF
@CecileRobertMichon Thanks for pointing that out, I wasn't aware.

It looks to me like the latest stuff is all about using Docker manifests and enabling multi-arch images. Is that a fair assessment? If it is, do you see implementing that as a requirement for a first pass at building and publishing an image through the promotion process?

I realize there are great examples of how to do this, since it's already done in CAPZ and CAPI. Would you be accepting of starting simple and not doing the manifest/buildkit approach, and tackling that when/if we do multi-arch images?

2020-12-15 20:54 UTC, CecileRobertMichon commented on images/capi/cloudbuild.yaml
> +      - PULL_BASE_REF=$_PULL_BASE_REF
The main advantage is that the docker buildkit approach is _much_ faster. Before we switched to that approach in CAPZ recently, or image pushing job was very flaky (see the difference between before and after the [PR](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1061/files) merged on Dec 1st: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/post-cluster-api-provider-azure-push-images).

To me, the improvement is worth the extra effort. Whether in this PR or a follow-up doesn't really matter but might as well get it right from the start if we aren't in a rush to merge this?

2020-12-18 21:51 UTC, codenrhoden commented on images/capi/cloudbuild.yaml
> +      - PULL_BASE_REF=$_PULL_BASE_REF
Thanks @CecileRobertMichon. That is definitely a speed up that is well worth it.

I've asked @SanikaGawhane to take the buildkit + `docker manifest` approach for now. I do still think we have the tag/version of the container image solved via a separate method. If we need to change that, that's okay of course, but I don't think it needs to be part of this PR.

2021-01-06 15:50 UTC, detiber commented on images/capi/cloudbuild.yaml
> +      - PULL_BASE_REF=$_PULL_BASE_REF
While `PULL_BASE_REF` might not be needed, the `_GIT_TAG` substitution is specified during the call go GCB: https://github.com/kubernetes/test-infra/tree/master/images/builder#gcb-builder

2021-01-06 16:28 UTC, codenrhoden commented on images/capi/cloudbuild.yaml
> +      - PULL_BASE_REF=$_PULL_BASE_REF
Looking through that Go code (in `main.go`) I still don't understand how it is used, and the README there isn't very helpful. I think I'll have to figure how to test this locally in order to understand it.

2021-01-06 16:29 UTC, codenrhoden commented
> I've asked @SanikaGawhane to take the buildkit + docker manifest approach for now. I do still think we have the tag/version of the container image solved via a separate method. If we need to change that, that's okay of course, but I don't think it needs to be part of this PR.

@SanikaGawhane Any luck with the `buildkit` approach? I see the latest commit doesn't have it.

2021-01-06 22:17 UTC, SanikaGawhane commented
/test pull-azure-vhds

2021-01-07 15:50 UTC, detiber commented on images/capi/cloudbuild.yaml
> +      - PULL_BASE_REF=$_PULL_BASE_REF
I think the main thing is that PROW sets the env var as `GIT_TAG`, and we are using `TAG`, so the substitution does that mapping so that we create the image with the correct tag, at least when triggered by a postsubmit job, such as: https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/k8s-staging-cluster-api.yaml#L14

As an aside, I believe the reason we are using PULL_BASE_REF in the CAPI jobs is to do the same thing for post submit jobs that are triggered for the branch vs the tag, so that the tag name associated with the branch is updated in the staging bucket.

2021-01-08 17:09 UTC, codenrhoden commented
At first blush, this looks good to me now. I still need to see if I can run the cloudbuild stuff locally to see how the `_GIT_TAG` stuff works I guess? That's the only piece I'm not understanding. It's a bit overkill/overcomplication IMO. We just want to tag the container with a version that we already know in our Makefile. 🤷‍♂️ 

/retest

2021-01-11 16:31 UTC, codenrhoden commented
I'm going to try and play with this this afternoon, but in the meantime, any other comments are welcome. Thanks for keeping up the work on this, @SanikaGawhane!

2021-01-14 18:39 UTC, codenrhoden reviewed
@SanikaGawhane I took this for another testdrive, and when I run `make docker-build`, nothing actually happens for me. It pulls the `dockerfile` container, and then... nothing. Does this work for you?  Here's what I see:

```sh
[trhoden@mbp ~/git/sigs.k8s.io/image-builder/images/capi (sg-image-promoter *)]$ TAG=dev-buildkit make docker-build
docker pull docker/dockerfile:1.1-experimental
1.1-experimental: Pulling from docker/dockerfile
Digest: sha256:de85b2f3a3e8a2f7fe48e8e84a65f6fdd5cd5183afa6412fff9caa6871649c44
Status: Image is up to date for docker/dockerfile:1.1-experimental
docker.io/docker/dockerfile:1.1-experimental
[trhoden@mbp ~/git/sigs.k8s.io/image-builder/images/capi (sg-image-promoter *)]$
```

But if I run the `docker build` command directly, it works just fine with buildkit. I'm not sure what the deal is here.

2021-01-14 18:39 UTC, codenrhoden commented on images/capi/Makefile
> +    DOCKER_BUILDKIT=1 docker build --build-arg PASSED_IB_VERSION=$(IB_VERSION) --build-arg ARCH=$(ARCH) . -t $(CONTROLLER_IMG)-$(ARCH):$(TAG)
Nit: this appears to have changed from a single tab to spaces. Let's make it consistent with all the others.

2021-01-14 18:42 UTC, codenrhoden commented on images/capi/Makefile
> +    DOCKER_BUILDKIT=1 docker build --build-arg PASSED_IB_VERSION=$(IB_VERSION) --build-arg ARCH=$(ARCH) . -t $(CONTROLLER_IMG)-$(ARCH):$(TAG)
Actually, this change explans my other comment. I thought I had tested it already, but I must have done something weird. When I change this to a single tab, this works for me.

2021-01-14 19:16 UTC, SanikaGawhane commented on images/capi/Makefile
> +    DOCKER_BUILDKIT=1 docker build --build-arg PASSED_IB_VERSION=$(IB_VERSION) --build-arg ARCH=$(ARCH) . -t $(CONTROLLER_IMG)-$(ARCH):$(TAG)
Fixed now!

2021-01-14 20:18 UTC, codenrhoden commented on images/capi/Makefile
> +	REGISTRY=$(STAGING_REGISTRY) $(MAKE) docker-build docker-push
@SanikaGawhane One more thing I'd like to see here, which is add `TAG=$(IB_VERSION)` at the beginning so that the container image is built with the correct tag, rather than the default `dev`. We can do this for just this Make target so it's correct if you do `release-staging`, but it is `dev` if you just do `make docker-build` yourself. Maybe that will change later, but the release target should definitely use the correct tag.

2021-01-14 23:03 UTC, SanikaGawhane commented on images/capi/Makefile
> +	REGISTRY=$(STAGING_REGISTRY) $(MAKE) docker-build docker-push
> @SanikaGawhane I took this for another testdrive, and when I run `make docker-build`, nothing actually happens for me. It pulls the `dockerfile` container, and then... nothing. Does this work for you?

@codenrhoden There was an extra character that caused an error in the way the `CONTROLLER_IMG` variable was being set. It should work now.

Referring to more previous discussions:
> Our makefile dynamically determines the version by setting the `IB_VERSION` variable:

I am leaving the `GIT_TAG` in place as of now (till we have more clarification) even though the above statement is true.

2021-01-15 16:03 UTC, codenrhoden requested changes
I don't think you meant to check in the `.idea` folder here. Please remove.

2021-01-15 16:03 UTC, codenrhoden commented on images/capi/Makefile
> +CONTROLLER_IMG ?= $(REGISTRY)$(IMAGE_NAME)
The removed `/` here needs to be added back. Otherwise you get this for a container name:

`gcr.io/k8s-staging-scl-image-buildercluster-node-image-builder-amd64:v0.1.6-169-g7c456fd04`.

2021-01-15 21:12 UTC, codenrhoden commented
/lgtm

@detiber and @CecileRobertMichon could you take a look at this again? I think this is good to go, or at least at a  place that we can merge and iterate. When running `make release-staging` now, you'd end up with a container like the following (built from Sanika's branch):

```
gcr.io/k8s-staging-scl-image-builder/cluster-node-image-builder-amd64:v0.1.6-169-g3cd852c4d
```

2021-01-15 21:44 UTC, CecileRobertMichon reviewed
lgtm

2021-01-16 04:49 UTC, codenrhoden approved these changes
I'll merge this in Tuesday morning (since Monday is holiday) if there are no further comments.

2021-01-16 04:57 UTC, codenrhoden commented
/hold
Just waiting until Tuesday
Forgot this repo treats GitHub review approvals as `/approve`

2021-01-19 16:55 UTC, codenrhoden commented
/hold cancel

2021-01-19 17:31 UTC, merged