Add EFI Support
kubernetes-sigs/image-builder pull request #482
Opened 2021-01-26 17:01 UTC by z4ce

What this PR does / why we need it:
This PR adds support for building OVAs that boot using EFI. We need EFI support for using DirectPathIO devices with more than 16GB of mapped memory. This is necessary for GPU devices.

I do wonder if EFI should be made the default, as I don't know any benefit to maintaining non-EFI images separately.

2021-01-26 19:05 UTC, z4ce commented
CLA Verified

2021-01-26 19:26 UTC, kkeshavamurthy commented on images/capi/Makefile
> +UBUNTU_VERSIONS			:=	ubuntu-1804 ubuntu-2004 ubuntu-2004-efi
Instead of adding a new target, can `firmware` var be passed through packer vars?

2021-01-26 20:29 UTC, z4ce commented on images/capi/Makefile
> +UBUNTU_VERSIONS			:=	ubuntu-1804 ubuntu-2004 ubuntu-2004-efi
It also needs different preseed file and boot command.. so I don't think so

2021-02-04 15:25 UTC, z4ce commented
/assign @detiber

2021-02-17 18:52 UTC, z4ce commented
@codenrhoden wondering if you got a chance to look at this?

2021-02-17 18:58 UTC, codenrhoden commented
> @codenrhoden wondering if you got a chance to look at this?

I haven't yet, but it is certainly on my radar. Thank you for pointing it out.

2021-02-18 19:07 UTC, kkeshavamurthy commented on images/capi/packer/ova/linux/ubuntu/http/base/preseed-efi.cfg
> +# d-i partman-efi/non_efi_system boolean false
Can these be removed?

2021-02-18 19:08 UTC, kkeshavamurthy commented on images/capi/packer/ova/ubuntu-2004-efi.json
> +  "boot_command_suffix": "/20.04/preseed-efi.cfg -- <wait><enter>initrd /install/initrd.gz<enter>boot<enter><wait>",
Since non-efi Ubuntu-X building uses floppy to provide preseed file, can we keep it consistent here please?

2021-02-18 19:11 UTC, kkeshavamurthy commented on images/capi/packer/ova/packer-node.json
> +        "../../hack/image-build-ova.py --firmware={{user `efi`}}  --stream_vmdk --node --vmx {{user `vmx_version`}} --eula ../../hack/ovf_eula.txt --ovf_template ../../hack/ovf_template.xml --vmdk_fi
should `--firmware={{user `efi`}}` be `--firmware={{user `firmware`}}` ?

2021-02-18 19:12 UTC, kkeshavamurthy commented on images/capi/packer/ova/packer-node.json
> +        "../../hack/image-build-ova.py --firmware={{user `efi`}} --node --vmx {{user `vmx_version`}} --eula ../../hack/ovf_eula.txt --ovf_template ../../hack/ovf_template.xml --vmdk_file {{user `buil
same as above

2021-02-18 19:12 UTC, kkeshavamurthy commented on images/capi/packer/ova/packer-node.json
> +        "./hack/image-build-ova.py --firmware={{user `efi`}} --stream_vmdk --node --vmx {{user `vmx_version`}} --eula ./hack/ovf_eula.txt --ovf_template ./hack/ovf_template.xml {{user `output_dir`}}"
same as above

2021-02-18 19:21 UTC, z4ce commented on images/capi/packer/ova/linux/ubuntu/http/base/preseed-efi.cfg
> +# d-i partman-efi/non_efi_system boolean false
Yeah they can be

2021-02-18 19:22 UTC, z4ce commented on images/capi/packer/ova/ubuntu-2004-efi.json
> +  "boot_command_suffix": "/20.04/preseed-efi.cfg -- <wait><enter>initrd /install/initrd.gz<enter>boot<enter><wait>",
I'm not sure what you mean.. I didn't change the way the preseed file was delivered... did a more recent commit change the preseed from http to floppy?

2021-02-18 19:28 UTC, z4ce commented on images/capi/packer/ova/packer-node.json
> +        "../../hack/image-build-ova.py --firmware={{user `efi`}}  --stream_vmdk --node --vmx {{user `vmx_version`}} --eula ../../hack/ovf_eula.txt --ovf_template ../../hack/ovf_template.xml --vmdk_fi
I'll look into these.. I probably forgot to commit this file or something when I changed the variable

2021-02-18 22:09 UTC, kkeshavamurthy commented on images/capi/packer/ova/ubuntu-2004-efi.json
> +  "boot_command_suffix": "/20.04/preseed-efi.cfg -- <wait><enter>initrd /install/initrd.gz<enter>boot<enter><wait>",
Yes it was changed recently in this [PR](https://github.com/kubernetes-sigs/image-builder/pull/497)

2021-02-18 22:31 UTC, kkeshavamurthy commented on images/capi/hack/image-build-ova.py
> +    parser.add_argument('--firmware', default='bios', help="Set to bios or efi. Defaults to bios")
Since `firmware` var is added in `packer-common`, we can just stick it in the mainfest and access it similar to other vars `FIRMWARE: build_data['firmware']` ? Then there will be no need of a new python arg & no changes to how `image-builder-ova.py` is called.

2021-02-18 22:41 UTC, z4ce commented on images/capi/hack/image-build-ova.py
> +    parser.add_argument('--firmware', default='bios', help="Set to bios or efi. Defaults to bios")
I'll try that. Should work.

2021-02-25 09:58 UTC, kkeshavamurthy commented on images/capi/packer/ova/packer-haproxy.json
> +
nit: can we please remove the extra lines.

2021-02-25 09:59 UTC, kkeshavamurthy commented on images/capi/packer/ova/packer-node.json
> +        "../../hack/image-build-ova.py  --stream_vmdk --node --vmx {{user `vmx_version`}} --eula ../../hack/ovf_eula.txt --ovf_template ../../hack/ovf_template.xml --vmdk_file {{user `build_version`}
nit: remove extra space.

2021-02-25 10:00 UTC, kkeshavamurthy commented on images/capi/hack/image-build-ova.py
> +      os.fsync(f.fileno())
This was working fine without the flush. Any reason for adding them?

2021-03-09 20:06 UTC, z4ce commented on images/capi/hack/image-build-ova.py
> +      os.fsync(f.fileno())
For some reason I keep getting checksum failure on the ova.. I thought it was a race but the flush and sync didn't fix it.. I'm just now getting back to this PR to figure out what is actually going on

2021-03-26 14:28 UTC, kkeshavamurthy commented
Hi @z4ce, did you get a chance to look at the issues you were having?

2021-04-07 07:24 UTC, kkeshavamurthy commented
@z4ce #580 should fix the OVA creation issues you were seeing. Can you please rebase and confirm?

CC: @codenrhoden

2021-04-07 12:30 UTC, perithompson commented
There will be some windows parts that we need to add Windows EFI support separately? Should i create a separate issue to track that?

2021-04-07 12:38 UTC, kkeshavamurthy commented
@perithompson Yes that would be best.

2021-04-16 06:50 UTC, kkeshavamurthy commented on images/capi/hack/ovf_template.xml
> +      <vmw:Config ovf:required="false" vmw:key="firmware" vmw:value="${FIRMWARE}"/>
Also does 
```<vmw:Config ovf:required="false" vmw:key="bootOptions.efiSecureBootEnabled" vmw:value="false"/>```
need to be set to `true`?

2021-04-19 22:22 UTC, codenrhoden requested changes
Hi @z4ce, thanks so much for putting this together. I think it's a capability that is becoming important. Do you think you'll have the bandwidth to address review comments and iterate on this feature?

I agree with you that it may make sense to make EFI be the default, but let's work up to that one over time. Addressing one of @kkeshavamurthy's comments, I do not think Secure Boot needs to be enabled by default with this change.

2021-04-19 22:22 UTC, codenrhoden commented on images/capi/Makefile
> +UBUNTU_VERSIONS			:=	ubuntu-1804 ubuntu-2004 ubuntu-2004-efi
Agreed that this would be nice, but it does seem like we are stuck with this for now. I take this as another data point in favor of creating a pre-processor that generates these files (a CLI).

2021-04-19 22:22 UTC, codenrhoden commented on images/capi/hack/image-build-ova.py
> +      os.fsync(f.fileno())
This can go away now, checksum issue has been fixed and was unrelated.

2021-04-19 22:22 UTC, codenrhoden commented on images/capi/packer/ova/linux/ubuntu/http/base/preseed-efi.cfg
> +      65536 65536 65536 linux-swap            \
I think having this swap partition is my main issue with the PR right now. We make sure all the other images *don't* have any swap space since K8s doesn't want that in the nodes. I wonder if as a first attempt we can just remove the swap partition and make the root partition consume the rest of the size?

2021-04-19 22:22 UTC, codenrhoden commented on images/capi/packer/ova/linux/ubuntu/http/base/preseed-efi.cfg
> +    in-target swapoff -a ; \
FYI, here is a place where swap is removed, so partitioning for is probably wasteful.

2021-04-20 04:30 UTC, z4ce commented
I've been meaning to get back to this PR, I just rebased it.. and I'll see if I can find a cluster tomorrow to give it a spin and make sure the rebase was successful. There were some files that were pretty heavily reformatted so hopefully I didn't miss a `{{user firmware}}` somewhere

2021-04-20 04:33 UTC, z4ce commented on images/capi/packer/ova/linux/ubuntu/http/base/preseed-efi.cfg
> +      65536 65536 65536 linux-swap            \
I'm fine with removing the swap.. honestly I just followed the partition pattern from somewhere else.. it's not necessary for the EFI support

2021-04-20 14:11 UTC, z4ce commented on images/capi/hack/ovf_template.xml
> +      <vmw:Config ovf:required="false" vmw:key="firmware" vmw:value="${FIRMWARE}"/>
No, at least not for my purposes.. maybe windows would need it?

2021-04-21 21:11 UTC, z4ce commented
@codenrhoden @kkeshavamurthy I verified this successfully built an image and no checksum errors 🎉

2021-04-26 06:20 UTC, kkeshavamurthy commented on images/capi/packer/ova/linux/ubuntu/http/base/preseed-efi.cfg
> +    in-target rm -f /etc/udev/rules.d/70-persistent-net.rules
```    
in-target apt-get purge --auto-remove -y ; \
in-target rm -rf /var/lib/apt/lists/*
```
Does ^^ need to be added at the end, similar to ubuntu-2004?

2021-04-26 06:24 UTC, kkeshavamurthy commented
@z4ce Thanks for updating the PR. 
FYI, it'll fail json-sort CI test. So please run `make json-sort` and update :)

2021-04-28 15:08 UTC, codenrhoden commented
/test json-sort-check
@kkeshavamurthy I'll have to look at the regex for this test to figure out why it didn't run on this PR. it certainly should have!

2021-04-28 15:11 UTC, codenrhoden commented on images/capi/packer/ova/linux/ubuntu/http/base/preseed-efi.cfg
> +    in-target rm -f /etc/udev/rules.d/70-persistent-net.rules
FWIW, those two lines were added in the other PRESEED to help out a usecase where I was using apt-cacher-ng to speed up builds and running into weird stale data. It's not strictly required, but it would be nice if they were consistent. I need to check if we can have more than one `include` in a preseed. Last time I look I remember finding that we couldn't, but I think I had a different use case then so maybe that's not right.

2021-04-28 15:11 UTC, codenrhoden commented on images/capi/packer/ova/packer-common.json
> +  "firmware": "bios"
as previously mentioned, please keep this in alphabetical order.

2021-04-28 15:11 UTC, codenrhoden commented on images/capi/packer/ova/packer-haproxy.json
> +      "memory": 2048,
alphabetical order.

2021-04-28 15:11 UTC, codenrhoden commented on images/capi/packer/ova/packer-haproxy.json
> +
no need for this extra space

2021-04-28 15:34 UTC, z4ce commented
Sorted the json

2021-04-29 15:33 UTC, codenrhoden commented
/ok-to-test
I hadn't noticed this was never given -- that's why the JSON sort check probably wasn't running...

I'm inclined to merge this at this point and iterate as needed. Thanks for the continuing to update, @z4ce

2021-04-29 16:33 UTC, z4ce commented
I had a quick look, and I don't see why this is failing. Variable is defined in `packer-common`, reference seem right in `packer-haproxy`.. some sort of order of operations thing?

2021-04-29 16:41 UTC, kkeshavamurthy commented on images/capi/packer/ova/packer-haproxy.json
> +      "firmware": "{{user `firmware`}}",
`firmware` is not an option in `vmware-iso` builder. That's why the test is failing.

2021-04-29 16:51 UTC, codenrhoden commented on images/capi/packer/ova/packer-haproxy.json
> +      "firmware": "{{user `firmware`}}",
dang, you beat me to it!

Yeah, looking at https://www.packer.io/docs/builders/vmware/vsphere-iso vs https://www.packer.io/docs/builders/vmware/iso, indeed `firmware` is not supported for the `vmware-iso` builder. This means we can't build EFI OVAs with the "local" builders, meaning Workstation or Fusion. Lame.

2021-04-29 16:58 UTC, codenrhoden commented
And just as a heads up, once the `validate` issue is fixed, you'll want to go ahead and squash this down to 1 commit. I understand the workflow of pushing changes 1-by-1, but once things are all wrapped up we want it as a single commit per "feature". Additionally, the first commit in this patchset contains [git merge conflict markers](https://github.com/kubernetes-sigs/image-builder/blob/0db0733096e01166225a63d7a7175281b57cc49a/images/capi/packer/ova/packer-haproxy.json#L132-L139), which we definitely don't want in the repo history.

2021-04-29 17:24 UTC, z4ce commented
I removed references to firmware from the vsphere-iso builders and rebased squashing the fix commits

2021-04-29 17:30 UTC, kkeshavamurthy commented
@z4ce , 
We need `firmware` references in `vsphere-iso` builders. 
We do not need `firmware` references in `vmware-iso` builders.

2021-04-29 19:26 UTC, z4ce commented
/retest

2021-04-30 16:20 UTC, codenrhoden commented
/test pull-azure-vhds
/lgtm

2021-04-30 17:11 UTC, codenrhoden commented
I think this gives us what we need to merge and iterate if/as needed. Thank you so much @z4ce !
/approve

2021-04-30 17:11 UTC, merged