Add documentation for container images
kubernetes-sigs/image-builder pull request #495
Opened 2021-02-05 01:24 UTC by SanikaGawhane

Adds a section in Image-Builder book on how to build and use container images to build your own custom images.
This tutorial lists steps for building AMIs, OVAs and Azure Images.

/cc @codenrhoden 
/cc @kkeshavamurthy

2021-02-08 20:51 UTC, codenrhoden requested changes
Thanks @SanikaGawhane. The first step towards really helping users simplify their workflows. =)

2021-02-08 20:51 UTC, codenrhoden commented on docs/book/src/capi/container-image.md
> +#Using the container image to building a custom image
You  need a space after the `#` here. Check out the preview here: https://deploy-preview-495--kubernetes-sigs-image-builder.netlify.app/capi/container-image.html

2021-02-08 20:51 UTC, codenrhoden commented on docs/book/src/capi/container-image.md
> +### Building and using a Docker Container Image
Since the section before is only 1 `#`, please make this `##`.

2021-02-08 20:51 UTC, codenrhoden commented on docs/book/src/capi/container-image.md
> +Latest container images can be found here - [Staging](gcr.io/k8s-staging-scl-image-builder/cluster-node-image-builder-amd64) and [GA](gcr.io/k8s-artifacts-prod/scl-image-builder/cluster-node-image-bu
In order for these to be external links, prefix them with `https://`. If you look at the Netlify preview, you'll see what's happening instead if you try to follow one of these links. :)

2021-02-08 20:51 UTC, codenrhoden commented on docs/book/src/capi/container-image.md
> +Run the docker build target of Makefile
Let's make `## Building Container Image` it's own section after `## Using Container Image`. I think most people interested in the image will be consumers-only.

2021-02-08 20:51 UTC, codenrhoden commented on docs/book/src/capi/container-image.md
> +
Can we structure this more like the following...

## Using Container Image

... describe how you can get the container image by doing a `docker pull`. `docker run` of course pulls it for you, but it gives some text to put here. I'd use the k8s-prod URL with a `v0.1.7` tag (which will be the first GA/prod image).

### Examples

#### AWS

Describe what you need in order to run the AWS builder. Which is that you need your credentials and to set an AWS region.  **if** you have AWS CLI configured already, you can do it by mounting `~/.aws`. But it should be possible to do this without having AWS CLI installed (remember "all pre-reqs" are supposed to be taken care of by the image). Give an example of using that method by setting env vars in a file and pass them in. This second method could be done in a follow-up PR if you like.

#### Azure

...what you have looks good

#### vSphere

....

2021-02-08 20:51 UTC, codenrhoden commented on docs/book/src/capi/container-image.md
> +    - A `.env` file to load environment variables `SUBSCRIPTION_ID`, `CLIENT_ID` and `CLIENT_SECRET`
Can you show an example env file?

2021-02-08 20:51 UTC, codenrhoden commented on docs/book/src/capi/container-image.md
> +    docker run -it --rm --env-file az-creds.env -v /Users/<user>/.azure/:/home/imagebuilder/.azure gcr.io/cluster-node-image-builder:dev build-azure-sig-ubuntu-2004
let's show this with a real registry path. people *will* copy and paste this.... :)

`gcr.io/k8s-staging-scl-image-builder/cluster-node-image-builder-amd64:v0.1.7`

2021-02-08 20:51 UTC, codenrhoden commented on docs/book/src/capi/container-image.md
> +- Vsphere OVA
*vSphere

2021-02-08 20:51 UTC, codenrhoden commented on docs/book/src/capi/container-image.md
> +    - `vsphere.json` configuration file with user and hypervisor credentials
Example of this file? What exactly do I need to put in it. It may be okay to link to https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/packer/ova/vsphere.json, and say that a *copy* of that needs to be filled out and passed in.

2021-02-08 20:51 UTC, codenrhoden commented on docs/book/src/capi/container-image.md
> +    - Docker's `--net=host` option to ensure http server starts with the host IP and not the docker container IP
Can you add that this implies that this can only be done from a Linux machine?

Hopefully we remove this limitation (needing `--net=host`) soon with @kkeshavamurthy work on Floppy.

2021-02-08 20:51 UTC, codenrhoden commented on docs/book/src/capi/container-image.md
> +    docker run -it --rm --net=host -v <complete path of vsphere.json>:/home/imagebuilder/packer/ova/vsphere.json gcr.io/cluster-node-image-builder-amd64:dev build-node-ova-vsphere-ubuntu-2004
please don't override `/home/imagebuilder/packer/ova/vsphere.json`, that makes the git repo dirty and shows up in the OVF metadata.

Instead do `-v <complete path of vsphere.json>:/home/imagebuilder/vsphere.json --env PACKER_VAR_FILES=/home/imagebuilder/vsphere.json`

2021-02-08 20:51 UTC, codenrhoden commented on docs/book/src/capi/container-image.md
> +In addition to this, further customizations can be done as discussed [here](https://image-builder.sigs.k8s.io/capi/capi.html#examples).
Make this link `./capi.md#customization`

2021-02-11 17:21 UTC, codenrhoden requested changes

2021-02-11 17:21 UTC, codenrhoden commented on docs/book/src/SUMMARY.md
> +  - [Using Container Images](capi/container-image.md)
nit: all the links above this start with `./`. Let's add that here to be consistent.

2021-02-11 17:21 UTC, codenrhoden commented on docs/book/src/capi/container-image.md
> +docker pull gcr.io/k8s-staging-scl-image-builder/cluster-node-image-builder-amd64:v0.1.7
I see you added the `v0.1.7` tag - thank you. but I do want to this to point to the prod registry, not the staging. So this should be `gcr.io/k8s-artifacts-prod/scl-image-builder/cluster-node-image-builder-amd64:v0.1.7`.

2021-02-11 17:21 UTC, codenrhoden commented on docs/book/src/capi/container-image.md
> +    docker run -it --rm -v /Users/<user>/.aws:/home/imagebuilder/.aws gcr.io/k8s-staging-scl-image-builder/cluster-node-image-builder-amd64:v0.1.7 build-ami-ubuntu-2004
same re: staging vs prod

2021-02-11 17:21 UTC, codenrhoden commented on docs/book/src/capi/container-image.md
> +        docker run -it --rm --env-file aws-creds.env gcr.io/k8s-staging-scl-image-builder/cluster-node-image-builder-amd64:v0.1.7 build-ami-ubuntu-2004
same

2021-02-11 17:21 UTC, codenrhoden commented on docs/book/src/capi/container-image.md
> +    docker run -it --rm --net=host -v <complete path of vsphere.json>:/home/imagebuilder/packer/ova/vsphere.json --env PACKER_VAR_FILES=/home/imagebuilder/vsphere.json gcr.io/k8s-staging-scl-image-bu
Close! You've added the `PACKER_VAR_FILES` part, but it's pointing at a file that doesn't exist because you didn't change the `-v` part to `-v <complete path of vsphere.json>:/home/imagebuilder/vsphere.json`.

2021-02-11 17:21 UTC, codenrhoden commented on docs/book/src/capi/container-image.md
> +    docker run -it --rm --net=host -v <complete path of vsphere.json>:/home/imagebuilder/packer/ova/vsphere.json --env PACKER_VAR_FILES=/home/imagebuilder/vsphere.json gcr.io/k8s-staging-scl-image-bu
and please change to the prod registry

2021-02-23 22:55 UTC, CecileRobertMichon commented on docs/book/src/capi/container-image.md
> +    - Additionally, you'll need an `az-creds.env` file to load environment variables `SUBSCRIPTION_ID`, `CLIENT_ID` and `CLIENT_SECRET`
These should be prefixed with `AZURE_`, ie. `AZURE_SUBSCRIPTION_ID`, etc.

I believe we also need `AZURE_TENANT_ID`

2021-02-23 22:56 UTC, CecileRobertMichon commented on docs/book/src/capi/container-image.md
> +    - If the Azure-CLI is already installed on your machine, you can simply mount the `~/.azure` folder that stores all the required credentials.
I'm not sure this is true, have you verified it works? It looks to be copy-pasted from AWS instructions above

2021-02-23 22:57 UTC, CecileRobertMichon commented on docs/book/src/capi/container-image.md
> +    - Additionally, you'll need an `az-creds.env` file to load environment variables `SUBSCRIPTION_ID`, `CLIENT_ID` and `CLIENT_SECRET`
Is this Additionally or Alternatively?

2021-02-23 23:02 UTC, CecileRobertMichon commented on docs/book/src/capi/container-image.md
> +      SUBSCRIPTION_ID=xxxxxxx
```commandline
export AZURE_SUBSCRIPTION_ID="<SubscriptionId>"
export AZURE_TENANT_ID="<Tenant>"
export AZURE_CLIENT_ID="<AppId>"
export AZURE_CLIENT_SECRET="<Password>"
```

2021-02-24 20:32 UTC, SanikaGawhane commented on docs/book/src/capi/container-image.md
> +    - If the Azure-CLI is already installed on your machine, you can simply mount the `~/.azure` folder that stores all the required credentials.
We have verified that it works. 
However, on inspecting closely, I realized we were using the `~/.azure` file mainly to get `AZURE_TENANT_ID`. However, exporting it using the `az_creds.env` avoids copying the `~/.azure` folder. 
This simplifies and cleans up the docker command further.

Thanks @CecileRobertMichon for your inputs.

2021-03-03 03:01 UTC, kkeshavamurthy commented on docs/book/src/capi/container-image.md
> +
Just to keep it consistent, can this be `commandline` as well?

2021-03-11 21:13 UTC, codenrhoden requested changes
Hi @SanikaGawhane.  Good news! `v0.1.7` has been successfully promoted to prod.

Bad news... I gave you bad advice on what the final prod URL would be. I forgot how the k8s.gcr.io vanity domain works.

For the prod images, in your docs, instead of using `https://gcr.io/k8s-artifacts-prod/scl-image-builder/cluster-node-image-builder-amd64:v0.1.7`, you need to use `https://k8s.gcr.io/scl-image-builder/cluster-node-image-builder-amd64:v0.1.7`

No need for the "k8s-artifacts-prod" part!

2021-03-19 15:30 UTC, codenrhoden commented on docs/book/src/capi/container-image.md
> +      AZURE_CLIENT_SECRET=xxxxxx
So this didn't actually work for me. I get this output when following these instructions:

```sh
Please run 'az login' to setup account.
Please run 'az login' to setup account.
Please run 'az login' to setup account.
Please run 'az login' to setup account.
Please run 'az login' to setup account.
Please run 'az login' to setup account.
Please run 'az login' to setup account.
```

I also had to map in the `~/.azure` folder. So long as you've already done `az login` on your host, you can map in the Azure config with:
`-v ~/.azure:/home/imagebuilder/.azure`

2021-03-19 22:25 UTC, codenrhoden commented
I'm good with this. We can always add more as things come up. :)

/lgtm
/approve

2021-03-19 22:25 UTC, merged