Added a variable to configure hard disk size
kubernetes-sigs/image-builder pull request #498
Opened 2021-02-09 11:26 UTC by perithompson

What this PR does / why we need it:
Add the ability to set a variable to define the disk size of ova files.

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #428 

**Additional context**
I have set defaults to the initial values 20GB for Linux and 80GB for Windows but this can be overridden using PACKER_FLAGS=-var=disk_size="40926" (size is in MB)

2021-02-09 15:41 UTC, perithompson commented
@codenrhoden I should have probably done this with my original PR can you take a look over the changes please?

2021-02-10 17:22 UTC, codenrhoden reviewed
I guess I'm not concerned about the alphabetical ordering -- too many things have snuck in already that aren't.

/lgtm

Will wait to see if there are any more comments. @kkeshavamurthy can you take a look?

2021-02-10 17:22 UTC, codenrhoden commented on images/capi/packer/ova/packer-haproxy.json
> +    "disk_size": "20480"
nit: this list is in alphabetical order - can we please keep it that way?

I'm not sure we need to add this for HAProxy since it's deprecated anyways, but it is good to be consistent. 👍

2021-02-10 17:35 UTC, kkeshavamurthy commented
/lgtm

2021-02-10 18:05 UTC, codenrhoden commented
/ok-to-test
/retest

2021-02-11 20:30 UTC, codenrhoden requested changes

2021-02-11 20:30 UTC, codenrhoden commented on images/capi/packer/ova/packer-haproxy.json
> +        "disk_size": "{{user `disk_size`}}"
so one general problem here... Now that the disk size going to packer (e.g. `20480`) is being passed to the OVA script via the manifest, we have a mismatch of units. The Packer size of `20480` is going with 20GB. But the units in the OVF metadata are already in GB (remember the old hard coded value was `20`, so what really ends up in the OVF is 20480GB, or 20TB:

```sh
$ ovftool --hideEula ubuntu-2004-kube-v1.18.15.ovf
<snip>

Deployment Sizes:
  Flat disks:   20480.00 GB
  Sparse disks: 3.77 GB
```

So I believe we need to update the OVF template to use units of `"byte * 2^20"` instead.

2021-02-17 09:41 UTC, perithompson commented
/retest

2021-02-17 11:52 UTC, perithompson commented on images/capi/hack/image-build-ova.py
> +
`'DISK_SIZE': convert_disk_size(build_data['disk_size']),`

@codenrhoden I've added this to convert the value back to the the size in GB for the ovf

2021-02-17 18:16 UTC, codenrhoden commented on images/capi/hack/image-build-ova.py
> +
This seems like a lot of work vs just changing `2^30` to `2^20` in the OVF template like I suggested. The number we're passing in has increased by a factor of 1024 (2^10), so it makes since to me to just change the template instead... A lot less work. :)

2021-02-19 13:01 UTC, perithompson commented on images/capi/hack/image-build-ova.py
> +
Sorry totally missed what you meant 😄

2021-02-19 13:02 UTC, perithompson commented
/retest

2021-02-24 10:34 UTC, perithompson commented
sorry i messed up my rebase

2021-02-24 16:11 UTC, perithompson commented
/retest

2021-02-26 21:12 UTC, codenrhoden commented on images/capi/hack/image-build-ova.py
> +import math
can we remove this import that is no longer needed?

2021-03-01 09:01 UTC, perithompson commented on images/capi/hack/image-build-ova.py
> +import math
good spot!

2021-03-01 09:03 UTC, perithompson commented on images/capi/packer/ova/packer-haproxy.json
> +    "disk_size": "20480"
ive sorted these alphabetically now

2021-03-01 09:03 UTC, perithompson commented on images/capi/packer/ova/packer-haproxy.json
> +    "disk_size": "20480"
ive sorted these alphabetically now 👍

2021-03-01 09:26 UTC, kkeshavamurthy commented on images/capi/packer/ova/packer-windows.json
> +      "disk_size": "{{user `disk_size`}}",
Hi Peri, Should 80G default for windows be set in `windows-X.json` or `packer-windows.json`? I do not see that in the vars list

2021-03-01 17:41 UTC, perithompson commented on images/capi/packer/ova/packer-windows.json
> +      "disk_size": "{{user `disk_size`}}",
Yep you are right, somewhere along the refactoring I must have lost that, thanks Kiran I'll get that added!

2021-03-01 17:47 UTC, perithompson commented on images/capi/packer/ova/packer-windows.json
> +      "disk_size": "{{user `disk_size`}}",
It should be there now!

2021-03-01 20:33 UTC, codenrhoden commented
/lgtm

2021-03-02 15:21 UTC, codenrhoden commented
@kkeshavamurthy care to take one more look at this before I approve?

2021-03-02 15:52 UTC, kkeshavamurthy commented
/lgtm

2021-03-02 16:57 UTC, codenrhoden commented
/approve

Thanks @perithompson !

2021-03-02 17:25 UTC, merged