WIP Adding Windows Goss support
kubernetes-sigs/image-builder pull request #563
Opened 2021-03-24 11:16 UTC by perithompson

What this PR does / why we need it:

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #532

**Additional context**
Add any other context for the reviewers

/sig windows
/cc @jsturtevant

2021-03-24 11:18 UTC, perithompson commented
@jsturtevant I thought we could iterate on this together, thank you for getting the hard bits of the goss components and the help you gave me yesterday, this passed on my first run today so I thought it was worth starting a very much WIP PR 😄

2021-03-26 16:27 UTC, jsturtevant commented on images/capi/packer/goss/goss-windows.yaml
> +    timeout: 0
There is a ton of things happening in the existing goss components.  It would be preferable to re-use as much as we can there, though we have to have distinct commands for the windows side due to locations and the need to use powershell. The other part is goss only supports the `command` part of [goss](https://github.com/aelsabbahy/goss/blob/master/docs/platform-feature-parity.md#matrix---testsassertions).  

The question I have is should these be backed into the existing files like https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/packer/goss/goss-command.yaml which would make sure everything is together but add some noise to the file? I am leaning towards yes for the same reason we ended up consolidating some of the windows config files into the linux side: when making an update it is easier to see them and include them.

2021-03-26 16:27 UTC, jsturtevant commented
Nice to see this passing:

```
[0;32m    vhd-windows-2019:     "summary": {[0m
[0;32m    vhd-windows-2019:         "failed-count": 0,[0m
[0;32m    vhd-windows-2019:         "summary-line": "Count: 3, Failed: 0, Duration: 2.503s",[0m
[0;32m    vhd-windows-2019:         "test-count": 3,[0m
[0;32m    vhd-windows-2019:         "total-duration": 2502808900[0m
[0;32m    vhd-windows-2019:     }[0m
[0;32m    vhd-windows-2019: }[0m
[1;32m==> vhd-windows-2019: Goss validate ran successfully[0m
[1;32m==> vhd-windows-2019: 
```

2021-03-26 19:00 UTC, perithompson commented on images/capi/packer/goss/goss-windows.yaml
> +    timeout: 0
yeah I agree, I'm trying to work out how much we can reuse but I'm not sure there is much that will just overlap,  We can use an if statement to keep things in the same file but without making it harder to understand for whats already there is going to be tough, I'm thinking for minimum checks we need to check
- binary versions
- cloudbase_metadata
- installed features
- hyper v
- windows updates ( although I think this is going to be HARD! if not impossible)
- services installed and in expected state?
any thoughts?

I adding services to goss for windows would help with overlap of somethings but as most are commands atm that could be tricky?

2021-03-29 14:40 UTC, perithompson commented
/retest

2021-03-29 16:53 UTC, perithompson commented
I've raised https://github.com/YaleUniversity/packer-provisioner-goss/pull/49 to deal with the fact I couldn't get the inline-vars to work with windows, it seems to be something to do with unmarshalling Json on the windows node, there still seems to be a problem with containerd on the path for these tests to pass and I'm not sure if there is a way to have a dynamic %systemdrive% using non "command" tests but starting to get there for a first pass, once the Provisioner Pull is merged. @jsturtevant if you can have a look at the style that would be good particularly the workaround for lack of services in windows

``` yaml
goss-vars.yaml
  common-windows-service:
    cloudbase-init:
      expected:
      - Manual
      - Stopped
    kubelet:
      expected: 
      - Manual 
      - Stopped
      - "/RequiredServices.+:.+containerd/"
    sshd:
      expected:
      - Automatic
      - Running

---
goss-services.yaml
{{ if eq .Vars.OS "windows"}} # Windows
# Workaround until windows services are added to goss
command:
{{range $name, $vers := index .Vars .Vars.OS "common-windows-service"}}
  "Windows Service - {{ $name }}":
    exec: powershell -command "(Get-Service {{ $name }} | select *)"
    exit-status: 0
    stdout: {{range $vers.expected}}
    - {{.}}
    {{end}}
{{end}}
{{range $name, $vers := index .Vars .Vars.OS .Vars.PROVIDER "windows-service"}}
  "Windows Service - {{ $name }}":
    exec: powershell -command "(Get-Service {{ $name }} | select *)"
    exit-status: 0
    stdout: {{range $vers.expected}}
    - {{.}}
    {{end}}
{{end}}
{{end}}
```


also @codenrhoden is there someone who would be interested in checking how I've integrated windows to the existing goss files to see if it looks ok before I go any further?

2021-04-01 12:21 UTC, perithompson commented
@jsturtevant Added some timeouts and also removed the non-interactive no profile flag that was slowing the commands down and causing them to fail, I suspect it runs everything concurrently and changing the powershell flags may speed this up?  I think this is good for a base to work on and ready for review go if the tests passed. /cc @codenrhoden

2021-04-09 08:45 UTC, perithompson commented
/cc @kkeshavamurthy 
/cc @codenrhoden

2021-04-09 10:50 UTC, kkeshavamurthy commented on images/capi/packer/ami/packer-windows.json
> +        "OS": "{{user `distribution` | lower}}",
Is this supposed to be `distribution` or `distro_name`?

2021-04-09 10:52 UTC, kkeshavamurthy commented on images/capi/packer/ami/packer-windows.json
> +        "GOSS_USE_ALPHA": "1"
Just curious, what does `GOSS_USE_ALPHA` enable?

2021-04-09 10:55 UTC, perithompson commented on images/capi/packer/ami/packer-windows.json
> +        "GOSS_USE_ALPHA": "1"
It's required for windows support, you can see it here 😄  [aelsabbahy/goss/docs/platform-feature-parity.md](https://github.com/aelsabbahy/goss/blob/master/docs/platform-feature-parity.md)

2021-04-09 10:55 UTC, kkeshavamurthy commented on images/capi/packer/goss/goss-command.yaml
> +    exit-status: 1
`exit-status: 1` ?

2021-04-09 10:56 UTC, perithompson commented on images/capi/packer/ami/packer-windows.json
> +        "OS": "{{user `distribution` | lower}}",
ah probably, ill check that out, azure uses distribution and everything else uses distro_name, need to get that consistent I think, I think you're right that aim uses distro_name

2021-04-09 10:57 UTC, perithompson commented on images/capi/packer/goss/goss-command.yaml
> +    exit-status: 1
annoyingly yes.... i think there is probably a way around it but when I run that command I get exit status 1 even though i get a result 🤯 @jsturtevant  I meant to ask you about this

2021-04-09 10:58 UTC, perithompson commented on images/capi/packer/goss/goss-command.yaml
> +    exit-status: 1
I think it's because there is no valid api-server when I run kubectl even though it's a local command

2021-04-09 15:38 UTC, codenrhoden commented on images/capi/packer/config/windows/goss-args.json
> +{
I don't see a need for this file since it is identical to `images/capi/packer/config/goss-args.json`. Just point to that one instead. Less duplication!

2021-04-09 15:38 UTC, codenrhoden commented on images/capi/packer/goss/goss-command.yaml
> +    exit-status: 1
Does the WIndows binary not have the `--client=true` flag? That's how you get it to not ask/show the version of the API server and leave it as a "local only" command.

2021-04-09 15:40 UTC, perithompson commented on images/capi/packer/config/windows/goss-args.json
> +{
oh oops, yes that was the original pass, must have not removed it!

2021-04-09 15:41 UTC, perithompson commented on images/capi/packer/goss/goss-command.yaml
> +    exit-status: 1
I thought i tried that and it didn't make any difference, i will try though, i may not have done it right

2021-04-09 19:10 UTC, jsturtevant commented on images/capi/packer/goss/goss-command.yaml
> +    exit-status: 1
I was thinking the same about `--client` flag.  There are also some strange behavior in powershell if you read the error codes wrong.  If the client flag doesn't work we can look into how goss handles the return codes.

2021-04-12 08:10 UTC, perithompson commented on images/capi/packer/ami/packer-windows.json
> +        "OS": "{{user `distribution` | lower}}",
Nope, seems that AMIs and Azure use distribution, I copied the windows OS in this file from the packer.json in the AMI provider as well, maybe this is something we should get an issue to tidy up?

2021-04-12 08:37 UTC, perithompson commented on images/capi/packer/goss/goss-command.yaml
> +    exit-status: 1
nope it was just me, not sure what i was doing wrong before but that's cleaned it up! thanks all!

2021-04-12 09:32 UTC, perithompson commented
Resolved all the comments, and the tests look good too 😄

2021-04-12 14:39 UTC, codenrhoden commented
Nice work @perithompson. I'd like to get https://github.com/kubernetes-sigs/image-builder/pull/585 in before merging this one, just to make sure that adding in the Windows tests doesn't break the templates for the Linux tests. That new CI check makes sure that we can generate/populate the GOSS templates for each provider/OS we build. Take a look at it and see what you think.

2021-04-12 15:56 UTC, jsturtevant reviewed
Thanks for adding this!  lgtm other than one minor formatting issue

2021-04-12 15:56 UTC, jsturtevant commented on images/capi/packer/goss/goss-vars.yaml
> +
nit: lots of extra white space

2021-04-13 10:04 UTC, perithompson commented
@codenrhoden I've added the windows templating test support but the prow output seems to jumble everything together so it looks like Linux is checking windows and vice version?  seems good if you run it on your workstation 👍

2021-04-14 08:44 UTC, perithompson commented
any further comments or does this look good now @codenrhoden @kkeshavamurthy @jsturtevant

2021-04-16 12:35 UTC, perithompson commented
/assign @codenrhoden

2021-04-16 16:10 UTC, codenrhoden requested changes
Great work @perithompson! I'm glad to see this get added, and it seems like you had no issues adding in the windows stuff to that Python script. Just a couple minor things I saw.

2021-04-16 16:10 UTC, codenrhoden commented on images/capi/packer/goss/goss-vars.yaml
> +photon:
This `photon` section is a duplicate (check out line 123 in your file).

2021-04-16 16:10 UTC, codenrhoden commented on images/capi/hack/generate-goss-specs.py
> +    if 'windows' in system:
I think there's a general simplification that can be made here... Just like we don't distinguish between Ubuntu 18.04 and Ubuntu 20.04 (there's nothing release specific in `goss-args`), I don't see anything release specific for Windows. I think in the `builds` map, you can just add `windows1`. THen this can become `if system == 'windows'`, and additional simplifications can be made.

2021-04-16 16:10 UTC, codenrhoden commented on images/capi/hack/generate-goss-specs.py
> +                        choices=['al2', 'centos', 'flatcar', 'photon', 'rhel', 'ubuntu', 'windows-2019', 'windows-2004'],
Similarly, this can just add `'windows'`. If there is a good reason *not* to take that approach, this list should match the `usage` description above, and right now it doesn't.

2021-04-26 08:46 UTC, perithompson commented on images/capi/hack/generate-goss-specs.py
> +                        choices=['al2', 'centos', 'flatcar', 'photon', 'rhel', 'ubuntu', 'windows-2019', 'windows-2004'],
I only have one `windows version` check which is 

``` yaml
{{ if eq .Vars.distribution_version "2019" }}
  Windows build version is high enough:
    exit-status: 0
    exec: powershell -command "(Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' -Name UBR).UBR -ge 1817"
    stdout:
    - "True"
    timeout: 30000
{{end}}
```

I'll have a think how i could rework this to a single windows but I did try before, it just made the code look a bit messy

2021-04-26 09:34 UTC, perithompson commented on images/capi/hack/generate-goss-specs.py
> +                        choices=['al2', 'centos', 'flatcar', 'photon', 'rhel', 'ubuntu', 'windows-2019', 'windows-2004'],
Ok ive reworked this, what do you think @codenrhoden @jsturtevant

2021-04-26 16:02 UTC, jsturtevant commented on images/capi/hack/generate-goss-specs.py
> +                        choices=['al2', 'centos', 'flatcar', 'photon', 'rhel', 'ubuntu', 'windows-2019', 'windows-2004'],
lgtm but i have less experience in the goss area

2021-04-28 12:50 UTC, perithompson commented
@codenrhoden anything else needed on this?

2021-04-28 14:59 UTC, codenrhoden commented
/approve
This looks good to me. I was able to look at the test output and see that it is generating all the expected permutations. nice work!
@kkeshavamurthy care to take a look for an LGTM?
I would like to see if this can be improved in the future in CI to log the output a bit better, such that each GOSS output immediately follows the command instead of all being jumbled together...

2021-04-29 16:34 UTC, kkeshavamurthy commented
Thanks for working on this @perithompson 
/lgtm

2021-04-29 16:36 UTC, merged