WIP: added windows build fixes and optimisations
kubernetes-sigs/image-builder pull request #623
Opened 2021-06-01 09:10 UTC by perithompson

What this PR does / why we need it:
Adding fixes for cloudbase template failures, kubernetes binary download retries and openSSH failed

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

2021-06-01 09:11 UTC, perithompson commented
/sig windows

2021-06-02 21:01 UTC, codenrhoden reviewed
The powershell optimization seems like a neat trick.

2021-06-02 21:01 UTC, codenrhoden commented on images/capi/hack/ensure-ansible.sh
> +pip3 install --user "ansible-base==2.10.9" --force-reinstall
Hmm, woud this really be different than the `_version` defined up above? I know Ansible went through some packaging changes recently. I'll have to check on that.

2021-06-02 21:02 UTC, codenrhoden commented
/assign @jsturtevant

2021-06-04 15:50 UTC, jsturtevant requested changes
Overall looks good. There are three different things happening here (ps optomization, updating paths, and fix updates. Could we split those in to different commits or even PR's?

2021-06-04 15:50 UTC, jsturtevant commented on images/capi/ansible/windows/roles/cloudbase-init/tasks/main.yml
> +    dest: '{{ tempdir.stdout | trim }}\CloudbaseInitSetup.msi'
Would putting the trim on the variables above make it so it isn't needed through out? something like:

```
win_shell: $env:TEMP.Trim()
```

2021-06-04 15:50 UTC, jsturtevant commented on images/capi/ansible/windows/node_windows.yml
> +      register: systemdrive
Like centralizing this logic. Thanks!

2021-06-04 15:50 UTC, jsturtevant commented on images/capi/ansible/windows/node_windows.yml
> +            $env:path = $old_path
Should we be setting the path permanently?  So this optimization is in place when the machines boot as nodes in capi?

2021-06-07 08:25 UTC, perithompson commented on images/capi/ansible/windows/node_windows.yml
> +            $env:path = $old_path
https://docs.ansible.com/ansible/latest/user_guide/windows_performance.html#fix-high-cpu-on-boot-for-vms-cloud-instances so it looks like we could do something like this, but I'm guessing CPU types are likely to change in most cloud use cases, but will be the same for most vcenters?  what do you think?

2021-06-11 15:29 UTC, perithompson commented
@jsturtevant i can get these split out into separate PRs or commits if you think its better but how do you think this looks, the source URL can be used to provide a link to the openssh cab file from the features on demand iso meaning you can run this behind a firewall now :) as everything can now be downloaded from a specified link?

2021-06-11 15:55 UTC, jsturtevant reviewed
Had a few comments but generally looks good. 

Can we add a pointer to how to get the Cab files in the docs?

2021-06-11 15:55 UTC, jsturtevant commented on images/capi/ansible/windows/roles/systemprep/tasks/ssh.yaml
> +    checksum: '4b47b07b5e634291fad8ebfe85dd6446d74896c7e391276c7953671af7ce918a'
I think this should be `openssh_checksum`?

2021-06-11 15:55 UTC, jsturtevant commented on images/capi/ansible/windows/roles/systemprep/tasks/ssh.yaml
> +- name: Create temporary download ssh directory
I think it will be cleaner to read here if  you split these steps out to a separate file `ssh-offline.yaml` and import when  `openssh_url != ""`

2021-06-11 17:51 UTC, perithompson commented on images/capi/ansible/windows/roles/systemprep/tasks/ssh.yaml
> +    dest: '{{ tempdir.stdout | trim }}\ssh\OpenSSH-Server-Package~31bf3856ad364e35~amd64~~.cab'
I think the filename is expected to be that but I'm happy to be wrong!

2021-06-11 17:51 UTC, perithompson commented on images/capi/ansible/windows/roles/systemprep/tasks/ssh.yaml
> +    checksum: '4b47b07b5e634291fad8ebfe85dd6446d74896c7e391276c7953671af7ce918a'
Yes you're right!!  I even put it in the defaults!

2021-06-11 17:57 UTC, perithompson commented on images/capi/ansible/windows/roles/systemprep/tasks/ssh.yaml
> +- name: Create temporary download ssh directory
Ok, yep you're probably right! Will separate!

2021-06-14 12:16 UTC, perithompson commented on images/capi/ansible/windows/roles/cloudbase-init/templates/cloudbase-init-unattend.conf
> +[DEFAULT]
yep that's what it was! I thought that maybe the line ending was erroring out the template

2021-06-15 14:19 UTC, perithompson commented
@jsturtevant PTAL at the new changes

2021-06-21 08:13 UTC, perithompson commented on images/capi/ansible/windows/roles/cloudbase-init/tasks/main.yml
> +    dest: '{{ tempdir.stdout | trim }}\CloudbaseInitSetup.msi'
the powershell trim results in a different ending to the ansible trim logic, a bit of a pain but I had hoped to do that too!

2021-06-22 21:16 UTC, jsturtevant reviewed
Looks good. One final question and a few minor nits.

I do think we should split the commits since we have a few different things going on in the PR.

2021-06-22 21:16 UTC, jsturtevant commented on images/capi/ansible/windows/node_windows.yml
> +            $env:path = $old_path
It wasn't clear but is type amd64?  You're probably right that we can't be certain.  Seems like a nice to have for anyone creating there own images where they do know this. Maybe create an issue to track?

2021-06-22 21:16 UTC, jsturtevant commented on images/capi/ansible/windows/roles/systemprep/tasks/ssh-offline.yaml
> +    dest: '{{ tempdir.stdout | trim }}\ssh\OpenSSH-Server-Package~31bf3856ad364e35~amd64~~.cab'
Maybe a comment about this package name? 

Did you test this against a build other than WS 2019? These are platform specific so I was wondering if this cab file name is different per platform.

2021-06-22 21:16 UTC, jsturtevant commented on images/capi/ansible/windows/roles/systemprep/tasks/ssh-offline.yaml
> +    path: '{{ tempdir.stdout | trim }}\ssh'
nit: missing new line

2021-06-24 09:47 UTC, perithompson commented on images/capi/ansible/windows/roles/systemprep/tasks/ssh-offline.yaml
> +    dest: '{{ tempdir.stdout | trim }}\ssh\OpenSSH-Server-Package~31bf3856ad364e35~amd64~~.cab'
Just tried this, you're right this only works on 2019 😞 but I cant find a cab file to use with 2004, are you about to ask someone in MSFT if there is somewhere we can get these from?

2021-06-24 18:24 UTC, jsturtevant commented on images/capi/ansible/windows/roles/systemprep/tasks/ssh-offline.yaml
> +    dest: '{{ tempdir.stdout | trim }}\ssh\OpenSSH-Server-Package~31bf3856ad364e35~amd64~~.cab'
The same pattern of getting the cab file should work. As of now the cab files are not available in another way, though some thought is going into enabling that scenario but it won't be quick.

I don't think we should block this on only supporting 2019, but should give clear doc that states how.  Does the name of this cab file matter? I would guess it doesn't but not 100% sure.  If not we could just name generically and the rest of this would still work.

2021-06-25 14:38 UTC, perithompson commented
@jsturtevant ive just reduced the scope of the PR and i was planning to move SSH to another PR how does that feel to you?  prefer simplifying it or do you think I should add SSH back in?

2021-06-25 16:46 UTC, jsturtevant commented
> @jsturtevant ive just reduced the scope of the PR and i was planning to move SSH to another PR how does that feel to you? prefer simplifying it or do you think I should add SSH back in?

I think doing ssh in a seperate PR makes sense. There are some few whitespace items but otherwise this is ready to go.

2021-06-28 14:05 UTC, perithompson commented on images/capi/ansible/windows/node_windows.yml
> +            $env:path = $old_path
I'm not 100% sure if this mean amd64 or CPU type for cloud provider CPUs?

2021-06-30 15:08 UTC, jsturtevant commented on images/capi/ansible/windows/node_windows.yml
> +            $env:path = $old_path
Can you create an issue to track this as a possible improvement and further investigation?

2021-06-30 15:11 UTC, jsturtevant commented
looked at the results and don't see anything in particular. @perithompson  Might be the timeout in goss that you mentioned you've seen once or twice?  Its the first time we have seen it here...

/test pull-azure-vhds

2021-07-01 14:17 UTC, perithompson commented
/retest

2021-07-02 16:48 UTC, jsturtevant commented on images/capi/ansible/windows/node_windows.yml
> +            $env:path = $old_path
https://github.com/kubernetes-sigs/image-builder/issues/644

2021-07-02 16:49 UTC, jsturtevant commented
/lgtm
/approve

2021-07-02 16:50 UTC, jsturtevant commented
/assign @codenrhoden

2021-07-12 07:57 UTC, perithompson commented
hey @codenrhoden any update on getting this merged? anything more you need from me?

2021-07-12 08:42 UTC, kkeshavamurthy commented
@perithompson since you mentioned goss is resource intensive on windows and hence it timesout often, do we want to bump the build VM size in Azure?

2021-07-12 17:50 UTC, codenrhoden commented
@perithompson sorry for the delay. I thought this was allowed to be merged just from from James' approval. I  missed that it had some files outside of `ansible/windows`.

/approve

Still would be interested in hearing your thoughts on whether a boosted VM size will help as well.

2021-07-13 14:35 UTC, perithompson commented
/retest

2021-07-14 10:58 UTC, perithompson commented
trying to see if i can stop this timeout

2021-07-14 12:05 UTC, perithompson commented
/retest

2021-07-14 13:42 UTC, perithompson commented
@jsturtevant i seemed to have got goss to pass but now I have another issue? any ideas?

2021-07-14 20:43 UTC, codenrhoden commented
The most recent failure looks like this:

```
    vhd-windows-2004: TASK [systemprep : Add required Windows Features] ******************************
    vhd-windows-2004: fatal: [default]: FAILED! => {"changed": false, "msg": "Failed to install Windows Feature: The request to add or remove features on the specified server failed.\r\nInstallation of one or more roles, role services, or features failed.\nOne or several parent features are disabled so current feature can not be enabled. Error: 0xc004000d\n"}
```

That's not something that was changed in this PR, so I wonder what's happening there?
The Azure PR job is currently holding up a few different PRs. I was hoping *this* PR would make it less flaky.

/lgtm

2021-07-14 20:43 UTC, codenrhoden commented
/test pull-azure-vhds

2021-07-15 08:21 UTC, perithompson commented
Good eyes @codenrhoden it looks like the base features of the Windows 2004 azure image could have changed?  @jsturtevant is that even possible?

2021-07-15 14:37 UTC, codenrhoden commented
/test pull-azure-vhds

Things have been passing/merging so far this morning.... 🤞

2021-07-15 15:27 UTC, jsturtevant commented
It is the same error: `Failed to install Windows Feature: The request to add or remove features on the specified server failed.`  I am not sure what this is and seems to be something changed with the base image.  I would propose to disable 2004 from CI to track down what is happening.

2021-07-15 15:29 UTC, codenrhoden commented
Oddly enough, a couple other PRs merged this morning and those tests were passing. So I wonder if there really is something in this PR that is changing a feature... No idea, just talking out loud. We can definitely take the skip 2004 route for now.

2021-07-16 07:42 UTC, perithompson commented
/retest

2021-07-16 08:32 UTC, perithompson commented
@codenrhoden 
```
    vhd-ubuntu-1804:         {
    vhd-ubuntu-1804:             "duration": 50879035,
    vhd-ubuntu-1804:             "err": null,
    vhd-ubuntu-1804:             "expected": [
    vhd-ubuntu-1804:                 "false"
    vhd-ubuntu-1804:             ],
    vhd-ubuntu-1804:             "found": [
    vhd-ubuntu-1804:                 "true"
    vhd-ubuntu-1804:             ],
    vhd-ubuntu-1804:             "human": "Expected\n    \u003cbool\u003e: true\nto equal\n    \u003cbool\u003e: false",
    vhd-ubuntu-1804:             "meta": null,
    vhd-ubuntu-1804:             "property": "running",
    vhd-ubuntu-1804:             "resource-id": "kubelet",
    vhd-ubuntu-1804:             "resource-type": "Service",
    vhd-ubuntu-1804:             "result": 1,
    vhd-ubuntu-1804:             "successful": false,
    vhd-ubuntu-1804:             "summary-line": "Service: kubelet: running:\nExpected\n    \u003cbool\u003e: true\nto equal\n    \u003cbool\u003e: false",
    vhd-ubuntu-1804:             "test-type": 0,
    vhd-ubuntu-1804:             "title": ""
    vhd-ubuntu-1804:         }, 
.....
    vhd-ubuntu-1804:     "summary": {
    vhd-ubuntu-1804:         "failed-count": 1,
    vhd-ubuntu-1804:         "summary-line": "Count: 58, Failed: 1, Duration: 1.653s",
    vhd-ubuntu-1804:         "test-count": 58,
    vhd-ubuntu-1804:         "total-duration": 1652791549
    vhd-ubuntu-1804:     } 
```

This failure was not Windows now this was Ubuntu so we are improving!

2021-07-16 08:33 UTC, perithompson commented
/retest

2021-07-16 16:58 UTC, jsturtevant commented
the latest failure was also Linux:

```
[0;32m    vhd-centos-7: TASK [setup : perform a yum update] ********************************************[0m
[0;32m    vhd-centos-7: fatal: [default]: FAILED! => {"
```

/retest

2021-07-16 17:48 UTC, merged