Add option to enable .local lookups via DNS
kubernetes-sigs/image-builder pull request #671
Opened 2021-07-30 17:40 UTC by randomvariable

What this PR does / why we need it:

Lot of folk using Photon are still using .local domains in contravention of the RFCs. This adds an option to enable resolution of .local via DNS rather than MulticastDNS.

As this is technically a leak, it's disabled by default.

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

2021-08-10 21:29 UTC, codenrhoden requested changes
Hi @randomvariable,

Thanks for looking into this and coming up with a way for users to use `.local`. I agree that it shouldn't be enabled by default. I do think we should add this variable to the table at https://github.com/kubernetes-sigs/image-builder/blob/master/docs/book/src/capi/capi.md#customization to document it's use? Or maybe since this is Photon specific, maybe it belongs in https://github.com/kubernetes-sigs/image-builder/blob/master/docs/book/src/capi/providers/vsphere.md instead? We don't really have a table there for provider-specific variables, but we don't have one for AWS, so there is an example: https://github.com/kubernetes-sigs/image-builder/blob/master/docs/book/src/capi/providers/aws.md#common-aws-options.

2021-08-10 21:29 UTC, codenrhoden commented on images/capi/hack/ensure-ansible.sh
> +ansible-galaxy collection install community.general:==3.4.0
While I get why this is here, it seems unrelated to this PR?

I think using the newer syntax (e.g. `community.general.ini_file`) is a laudable goal, and an upgrade we need to do, I'd rather not see it mixed in piecemeal. I find it harder to read (but that may just be me, happy to hear other's opinions). For this particular PR, I'd rather see the changes made just `ini_file` until we make a bigger, across the board bump in Ansible. Thoughts?

2021-08-11 12:51 UTC, randomvariable commented on images/capi/hack/ensure-ansible.sh
> +ansible-galaxy collection install community.general:==3.4.0
Does `ini_file` still work? The Ansible docs have removed mention of it.

2021-08-11 13:04 UTC, randomvariable commented on images/capi/hack/ensure-ansible.sh
> +ansible-galaxy collection install community.general:==3.4.0
Reverted to the 2.9 docs version

2021-08-11 19:32 UTC, codenrhoden commented
Thanks for the docs updates!

/lgtm
/approve

2021-08-11 19:35 UTC, merged