Added the ability to install Win32-OpenSSH from Github
kubernetes-sigs/image-builder pull request #687
Opened 2021-09-03 08:48 UTC by perithompson

What this PR does / why we need it:
Installing OpenSSH from a Windows feature will not work when building in air-gapped environments.  To achieve this, this PR adds the ability to specify a ssh_source_url for the OpenSource Win32-OpenSSH port available on Github.

Which issue(s) this PR fixes: 
Fixes #621 

**Additional context**
If no ssh_source_url is specified OpenSSH will be install from MSFT updates as normal so no changes are required in CI

/sig windows

2021-09-03 08:51 UTC, perithompson commented
/cc @jsturtevant 
/cc @jayunit100

2021-09-09 05:08 UTC, hxietkg commented
Hope this PR merged soon

2021-09-13 08:18 UTC, perithompson commented
@jsturtevant are you able to take a look at this please?

2021-09-21 00:11 UTC, jsturtevant commented
Sorry for the delay was on a long vacation!

/lgtm 
/approve

2021-09-21 00:36 UTC, jsturtevant commented
/assign @codenrhoden

2021-09-30 16:03 UTC, codenrhoden requested changes
I just have the one comment on the copyright year change that I don't think is necessary.

Going through this, I'm struck that our process could use improvement because I think @jsturtevant's `/approve` should have been enough. We want Windows to be able to iterate independently and more quickly. I'm thinking we should add an `OWNERS` file to allow the `image-builder-windows-maintainers` alias approval rights in both `packer/config/windows` and `docs/`. Right now, both of these are defaulting to just the top-level `OWNERS` file, which doesn't seem like what we want here. Thoughts?

2021-10-01 17:03 UTC, jsturtevant commented on images/capi/ansible/windows/roles/systemprep/tasks/main.yml
> +# Copyright 2021 The Kubernetes Authors.
I am not sure on the guidance, I have been asked to update it in the past.

2021-10-01 17:05 UTC, jsturtevant commented
> Going through this, I'm struck that our process could use improvement because I think @jsturtevant's `/approve` should have been enough.

agree, in addition I've been blocked on the prs if it requires updates to the `makefile`. I don't know the best solution but adding the permissions you suggested would be a good start.

2021-10-05 08:42 UTC, perithompson commented on images/capi/ansible/windows/roles/systemprep/tasks/main.yml
> +# Copyright 2021 The Kubernetes Authors.
I've been asked a couple of times in the k8s codebase to update the copyright when I've modified the file.  I wonder if there is anything telling us when to update this copyright notice?

2021-10-05 11:18 UTC, nikhita commented on images/capi/ansible/windows/roles/systemprep/tasks/main.yml
> +# Copyright 2021 The Kubernetes Authors.
> As a general rule, we don't update the copyright year when files are modified.

This is correct. :+1: 

Copyright year is not updated when files are modified.

2021-10-06 08:58 UTC, perithompson commented on images/capi/ansible/windows/roles/systemprep/tasks/main.yml
> +# Copyright 2021 The Kubernetes Authors.
removed this copyright change, thanks @nikhita

2021-10-06 15:18 UTC, perithompson commented
@jsturtevant @codenrhoden PTAL

2021-10-06 17:24 UTC, merged