Adding virtualbox local build for local environment base box
kubernetes-sigs/image-builder pull request #699
Opened 2021-09-18 01:16 UTC by knabben

What this PR does / why we need it:
This PR adds a local build using VirtualBox hypervisor, packaged boxes are used directly on development environments like `kubernetes-sigs/sig-windows-dev-tools`.

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #https://github.com/kubernetes-sigs/image-builder/issues/698

**Additional context**
Add any other context for the reviewers

2021-09-18 07:19 UTC, perithompson commented
/retest

2021-09-18 07:27 UTC, perithompson commented
Thanks for this @knabben, been thinking about this for a while, think this is brilliant!

2021-09-18 07:34 UTC, perithompson requested changes
Just the file path to clean up and would you be able to add a clean target in the makefile for clean-vbox that removes the created outputs similar to clean-ova

2021-09-18 07:34 UTC, perithompson commented on images/capi/packer/vbox/windows-2019.json
> +  "os_iso_url": "file:/home/knabben/.img/win1.iso"
Can we make this a more generic file path

2021-09-21 19:24 UTC, jsturtevant commented on images/capi/Makefile
> +
nit: extra line

2021-09-21 19:26 UTC, jsturtevant commented on images/capi/Makefile
> +
nit: extra line

2021-09-21 19:27 UTC, jsturtevant commented on images/capi/packer/vbox/OWNERS
> +  - cluster-api-vsphere-maintainers
since this is primarily for windows, could we add `image-builder-windows-maintainers`

2021-09-21 19:28 UTC, jsturtevant commented on images/capi/packer/vbox/packer-common.json
> +  "guestinfo_datasource_slug": "https://raw.githubusercontent.com/vmware/cloud-init-vmware-guestinfo",
does this only work with vmware?

2021-09-21 19:35 UTC, jsturtevant commented on images/capi/packer/vbox/windows/disable-winrm.ps1
> +Stop-Service winrm
Winrm is required by packer/ansible. What is this doing?

2021-09-21 19:35 UTC, jsturtevant commented on images/capi/packer/vbox/windows/disable-winrm.ps1
> +Stop-Service winrm
ah I see it is disabled and re-enabled?

2021-09-21 19:36 UTC, jsturtevant commented on images/capi/packer/vbox/windows/sysprep.ps1
> +Write-Output '>>> Sysprepping VM ...'
Maybe not for this PR but we should see if we can re-use some of the sysprep scripts we have. I think we have one for ami, azure, and vmware now...

2021-09-21 20:33 UTC, knabben commented on images/capi/Makefile
> +RAW_CLEAN_TARGETS := $(subst build-,clean-,$(RAW_BUILD_TARGETS))
yes, this is a bug not related with the PR, should it moved to another PR?

2021-09-21 20:35 UTC, knabben commented on images/capi/packer/vbox/packer-windows.json
> +    "wins_url": "https://github.com/rancher/wins/releases/download/v{{user `wins_version`}}/wins.exe"
I will review these variables, not all are being used..

2021-09-21 20:38 UTC, knabben commented on images/capi/packer/vbox/windows/sysprep.ps1
> +Write-Output '>>> Sysprepping VM ...'
For Windows a few other scripts (besides sysprep) are shared between both targets (OVA and vbox), but yea makes sense to standardize across them

2021-09-21 20:39 UTC, knabben commented on images/capi/packer/vbox/windows/windows-2019/autounattend.xml
> +Windows Server 2019 Answer File Generator
For now, it is the same, but maybe it's too early to start sharing them and templating, so mostly copying the files for now

2021-09-21 20:40 UTC, knabben commented on images/capi/packer/vbox/windows/disable-winrm.ps1
> +Stop-Service winrm
Yes, this is the default behavior already, checking if this is necessary.

2021-09-22 16:03 UTC, jsturtevant commented on images/capi/packer/vbox/windows/sysprep.ps1
> +Write-Output '>>> Sysprepping VM ...'
created an issue to track https://github.com/kubernetes-sigs/image-builder/issues/700

2021-09-22 20:39 UTC, knabben commented
/test pull-azure-sigs

2021-09-23 09:40 UTC, perithompson commented on images/capi/packer/vbox/windows/disable-winrm.ps1
> +Stop-Service winrm
im not sure this is actually required, it was to reset everything to a neural state but i think it may not be needed, I've been meaning to go through the answer file scripts and clean them up, i think there is likely a lot we can trim in there for server core

2021-09-23 09:45 UTC, perithompson commented on images/capi/packer/vbox/packer-common.json
> +  "guestinfo_datasource_slug": "https://raw.githubusercontent.com/vmware/cloud-init-vmware-guestinfo",
my guess this is taken from packer-node in the ova directory, we don't use it for packer-windows.json so we may be able to remove this?  cloudbase-init works differently to cloud-init as it has services instread

2021-09-23 16:24 UTC, jsturtevant commented on images/capi/Makefile
> +RAW_CLEAN_TARGETS := $(subst build-,clean-,$(RAW_BUILD_TARGETS))
its minor but would be cleaner to have in a separate PR.  @codenrhoden do you have a preference?

2021-10-09 12:48 UTC, knabben commented
/retest

2021-10-09 15:34 UTC, knabben commented
/test pull-azure-sigs

2021-12-13 22:58 UTC, jsturtevant commented
@knabben Anything else to do for this?  I am fine with most of this but would like to understand if `"cloudbase_metadata_services_unattend": "cloudbaseinit.metadata.services.vmwareguestinfoservice.VMwareGuestInfoService",` is needed otherwise we can are good.

2021-12-16 16:28 UTC, jsturtevant commented on images/capi/Makefile
> +	packer build $(if $(findstring windows,$@),$(PACKER_WINDOWS_NODE_FLAGS),$(PACKER_NODE_FLAGS)) -var-file="packer/vbox/packer-common.json" -var-file="$(abspath packer/vbox/$(subst build-node-vbox-loca
This looks like it might have made it back in via rebase?  or is it needed?

2021-12-16 16:31 UTC, jsturtevant commented on images/capi/packer/vbox/packer-windows.json
> +        "PROVIDER": "ova",
```suggestion
        "PROVIDER": "virtualbox",
```

2021-12-16 16:33 UTC, jsturtevant commented on images/capi/packer/vbox/windows-2004.json
> +  "build_name": "windows-2004",
lets drop 2004, it went out of support this week

2021-12-16 16:35 UTC, jsturtevant commented on images/capi/Makefile
> +	packer build $(if $(findstring windows,$@),$(PACKER_WINDOWS_NODE_FLAGS),$(PACKER_NODE_FLAGS)) -var-file="packer/vbox/packer-common.json" -var-file="$(abspath packer/vbox/$(subst build-node-vbox-loca
This looks like it might have made it back in via rebase? or is it needed?
```suggestion
	packer build $(if $(findstring windows,$@),$(PACKER_WINDOWS_NODE_FLAGS),$(PACKER_NODE_FLAGS)) -var-file="packer/vbox/packer-common.json" -var-file="$(abspath packer/vbox/$(subst build-node-vbox-local-,,$@).json)"  -only=virtualbox-iso $(ABSOLUTE_PACKER_VAR_FILES) packer/vbox/packer-$(if $(findstring windows,$@),windows).json
```

2021-12-16 16:35 UTC, jsturtevant commented on images/capi/Makefile
> +	packer validate $(if $(findstring windows,$@),$(PACKER_WINDOWS_NODE_FLAGS),$(PACKER_NODE_FLAGS)) -var-file="packer/ova/packer-common.json" -var-file="$(abspath packer/vbox/$(subst validate-node-vbox
```suggestion
	packer validate $(if $(findstring windows,$@),$(PACKER_WINDOWS_NODE_FLAGS),$(PACKER_NODE_FLAGS)) -var-file="packer/ova/packer-common.json" -var-file="$(abspath packer/vbox/$(subst validate-node-vbox-local-,,$@).json)" -only=virtualbox-iso $(ABSOLUTE_PACKER_VAR_FILES) packer/vbox/packer-$(if $(findstring windows,$@),windows).json
```

2021-12-16 17:32 UTC, knabben commented on images/capi/packer/vbox/vagrantfile-windows_2019.template
> +        v.customize ["modifyvm", :id, "--memory", 2048]
6Gb is enough from my tests

2021-12-16 17:47 UTC, jsturtevant commented
/lgtm

2021-12-17 20:47 UTC, jsturtevant commented
/assign @perithompson @codenrhoden

2021-12-26 20:39 UTC, knabben commented
/retest

2021-12-28 17:12 UTC, knabben commented
/test-pull-ova

2022-01-04 17:51 UTC, jsturtevant commented
/retest

/assign @perithompson @codenrhoden

2022-01-06 13:38 UTC, perithompson commented
it looks like the vsphere problems are connectivity problems, but the new builder looks ok to me!

/lgtm

2022-01-06 14:05 UTC, knabben commented
/test pull-ova-all

2022-01-07 17:30 UTC, codenrhoden requested changes
HI @knabben . sounds like Windows folks are excited to see this come in! Thanks for the addition.

It looks like a lot of comments from me, but it's really just two main things. A few clean ups in the Makefile, and then in the `packer-common.json` file, there are a lot of entries that are unused, or not relevant to the virtualbox builder. It looks like it was just copied from the VMware/OVA builder. Some of them may make sense for future Linux targets, but if they aren't supported by the VirtualBox builder at all, I think seeing them there is just confusing.

2022-01-07 17:30 UTC, codenrhoden commented on images/capi/Makefile
> +# Copyright 2021 The Kubernetes Authors.
The copyright header is only set on file creation. It is not updated when a file is updated. Please set back to 2019.

2022-01-07 17:30 UTC, codenrhoden commented on images/capi/Makefile
> +	hack/ensure-goss.sh
any interest in adding an `ensure-vbox` script that makes sure that vbox is installed? Doesn't have to install it for you, just make sure it's present? Not sure if that's an easy thing to do or not... Could be done as a follow-on. Not trying to hold this up.

2022-01-07 17:30 UTC, codenrhoden commented on images/capi/Makefile
> +NODE_VBOX_LOCAL_BUILD_NAMES			:=	$(addprefix node-vbox-local-,$(WINDOWS_VERSIONS))
I don't think "node" is necessary in the target names here for vbox. if you look at the output of `make help`, you'll see that "node" is only used with OVA targets. This was because OVA targets had two images it could build -- the node image, and the haproxy image. Thankfully haproxy is about to be removed since it is no longer used by CAPV.

2022-01-07 17:30 UTC, codenrhoden commented on images/capi/Makefile
> +validate-node-vbox-local-windows-2019: ## Validates Windows Server 2019 Node VirtualBox Packer config w local hypervisor
even though it seems silly, let's add the `validate-vbox-all` target. We do this so that we can add it as a dependency in `validate-all`, which is missing right now (just below this). We want vbox to be included when calling that target.

2022-01-07 17:30 UTC, codenrhoden commented on images/capi/Makefile
> +
`make clean` is basically acting like a `make clean-all` right now. So let's please add `$(VBOX_CLEAN_TARGETS)` to `clean`. You'll see that OVA and QEMU are there now.

2022-01-07 17:30 UTC, codenrhoden commented on images/capi/packer/vbox/packer-common.json
> +  "convert_to_template": "false",
This appears unused in the vbox buiilder.

2022-01-07 17:30 UTC, codenrhoden commented on images/capi/packer/vbox/packer-common.json
> +  "cpu_cores": "1",
this appears unused. I don't see a way to set cores per cpu in vbox builder.

2022-01-07 17:30 UTC, codenrhoden commented on images/capi/packer/vbox/packer-common.json
> +  "disk_type_id": "0",
all three `disk_*` vars here are unused.

2022-01-07 17:30 UTC, codenrhoden commented on images/capi/packer/vbox/packer-common.json
> +  "firmware": "bios",
`firmware` is supported by the vbox builder, but this doesn't appear to be passed through? If we don't want to allow a user to change this `efi`, we shouldn't expose it as a variable. If we do want that, please wire it through in the packer-windows.json file.

2022-01-07 17:30 UTC, codenrhoden commented on images/capi/packer/vbox/packer-common.json
> +  "format": "",
unused

2022-01-07 17:30 UTC, codenrhoden commented on images/capi/packer/vbox/packer-common.json
> +  "headless": "true",
currently unused. but vbox builder supports it, so wire it through?

2022-01-07 17:30 UTC, codenrhoden commented on images/capi/packer/vbox/packer-common.json
> +  "insecure_connection": "false",
unused

2022-01-07 17:30 UTC, codenrhoden commented on images/capi/packer/vbox/packer-common.json
> +  "network": "",
unusec

2022-01-07 17:30 UTC, codenrhoden commented on images/capi/packer/vbox/packer-common.json
> +  "remote_username": "",
remove all `remote_*` vars here.

2022-01-07 17:30 UTC, codenrhoden commented on images/capi/packer/vbox/packer-common.json
> +  "skip_compaction": "false",
unused.

2022-01-07 17:30 UTC, codenrhoden commented on images/capi/packer/vbox/packer-common.json
> +  "ssh_username": "builder",
all the `ssh_*` vars are currently unused. I'm guessing because we are only adding Windows right now. If we think we'll ever go beyond Windows, I guess it's okay to leave these. Otherwise I'd remove them.

2022-01-07 17:30 UTC, codenrhoden commented on images/capi/packer/vbox/packer-common.json
> +  "vnc_port_min": "5900"
Kind of the same for `vnc_*` here. There not used anywhere, but make sense if we are going to support Linux machines in the future.

2022-01-07 17:30 UTC, codenrhoden commented on images/capi/packer/vbox/windows/disable-network-discovery.cmd
> +netsh advfirewall firewall set rule group="Network Discovery" new enable=No
@jsturtevant did you ever get this one resolved?

2022-01-07 17:30 UTC, codenrhoden commented on images/capi/packer/vbox/windows/disable-winrm.ps1
> +Stop-Service winrm
did this ever get resolved, @jsturtevant @perithompson ?

2022-01-17 15:14 UTC, knabben commented on images/capi/packer/vbox/windows/disable-winrm.ps1
> +Stop-Service winrm
Removing this part. does not seems used for vbox.

2022-01-17 15:15 UTC, knabben commented on images/capi/packer/vbox/windows/disable-network-discovery.cmd
> +netsh advfirewall firewall set rule group="Network Discovery" new enable=No
Removing this part, does not seems required for vbox

2022-01-17 15:18 UTC, knabben commented on images/capi/Makefile
> +	hack/ensure-goss.sh
I prefer to do in another PR.

2022-01-20 15:51 UTC, codenrhoden commented
I see the correct output in the `packer-validate` job now. This is looking good to me. I'd like for a windows maintainer to take another look (though it looks like @perithompson gave this an /lgtm at one point).
/lgtm
/assign @jsturtevant 

The OVA job is failing, but not related to this PR and is non-blocking.
The GOSS populate job must have been triggered from a previous version of this PR, as it is no longer triggered by any of the changed files and is non-required.
It's worth pointing out, though, if GOSS tests *are* running as part of this build, we should add vbox into the `hack/generate-goss-specs.py` script so that it runs as part of CI. Right now, only AWS, Azure, and vSphere builders are having their GOSS variables validated.

2022-01-20 20:12 UTC, knabben commented
> It's worth pointing out, though, if GOSS tests _are_ running as part of this build, we should add vbox into the `hack/generate-goss-specs.py` script so that it runs as part of CI. Right now, only AWS, Azure, and vSphere builders are having their GOSS variables validated.

I will open an issue for it. thanks

2022-01-21 16:30 UTC, jsturtevant commented on images/capi/Makefile
> +	hack/ensure-goss.sh
#784 for tracking

2022-01-21 16:42 UTC, jsturtevant commented
/lgtm
/approve

Thanks for hanging in there on this one @knabben. Great to see it being used in https://github.com/kubernetes-sigs/sig-windows-dev-tools to help users create windows environments!

2022-01-21 17:13 UTC, merged