Make debug_tools configurable
kubernetes-sigs/image-builder pull request #751
Opened 2021-12-03 14:15 UTC by hxietkg

What this PR does / why we need it:
debug_tools is always true, and not configurable, we need an option to disable it.

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Add any other context for the reviewers

2021-12-08 19:22 UTC, codenrhoden commented
/ok-to-test

2021-12-13 22:52 UTC, jsturtevant commented on images/capi/packer/ova/packer-windows.json
> +    "debug_tools": "true"
This just needs to be sorted alphabetically.  We should add it to the https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/packer/config/windows/common.json file to keep as default for all providers. With the new field being passed through the Azure configs didn't get the debug files on the CI builds.

2021-12-13 22:53 UTC, jsturtevant requested changes
We should add the `debug_tools=true` it to the https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/packer/config/windows/common.json file to keep as default for all providers. With the new field being passed through the Azure configs didn't get the debug files on the CI builds.

2021-12-13 22:53 UTC, jsturtevant commented
/sig windows

2021-12-15 07:19 UTC, hxietkg commented on images/capi/packer/ova/packer-windows.json
> +    "debug_tools": "true"
done

2021-12-16 03:23 UTC, hxietkg commented
/retest

2022-01-04 06:41 UTC, hxietkg commented
/retest-required

2022-01-04 17:05 UTC, codenrhoden commented
/lgtm
/assign @jsturtevant

2022-01-06 21:22 UTC, jsturtevant commented
/approve

2022-01-07 17:36 UTC, codenrhoden commented
/approve

2022-01-07 19:04 UTC, merged