Add support for OCI Images
kubernetes-sigs/image-builder pull request #754
Opened 2021-12-07 04:15 UTC by shyamradhakrishnan

What this PR does / why we need it:
This PR adds support for Oracle Cloud Infrastructure(OCI) support in image-builder project. We are starting off with support to Ubuntu 18.04/20.04 and Oracle Linux 8 image.

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): Fixes #

**Additional context**
Uses OCI packer support similar to other providers.

2021-12-08 22:04 UTC, CecileRobertMichon commented
/ok-to-test

2021-12-08 22:05 UTC, CecileRobertMichon commented on docs/book/src/capi/providers/oci.md
> +# Building Images for Oracle Cloud Infrastructure (OCI)
the page needs to be added to https://github.com/kubernetes-sigs/image-builder/blob/f3b6852ae8efd0b0eb9d4293925b4b9e9dae18e4/docs/book/src/SUMMARY.md to show up in the book TOC

2021-12-09 02:23 UTC, shyamradhakrishnan commented
/retest

2021-12-09 03:10 UTC, shyamradhakrishnan commented
/retest

2021-12-09 03:12 UTC, shyamradhakrishnan commented on docs/book/src/capi/providers/oci.md
> +# Building Images for Oracle Cloud Infrastructure (OCI)
Thanks @CecileRobertMichon , fixed that

2021-12-09 16:32 UTC, CecileRobertMichon commented
@shyamradhakrishnan since we don't have any PR tests in place that run this right now, are you able to share the output of a local run so we know this works / for the record?

2021-12-09 17:43 UTC, shyamradhakrishnan commented
[oracle-linux-8.txt](https://github.com/kubernetes-sigs/image-builder/files/7687273/oracle-linux-8.txt)
[ubuntu-18.04.txt](https://github.com/kubernetes-sigs/image-builder/files/7687274/ubuntu-18.04.txt)
[ubuntu-20.04.txt](https://github.com/kubernetes-sigs/image-builder/files/7687275/ubuntu-20.04.txt)
Sure @CecileRobertMichon I have uploaded the make output of the images. I hope this is what you wanted us to share, if not my apologies, can you please explain a bit more on what test you want us to run?

2021-12-13 18:24 UTC, CecileRobertMichon commented
/lgtm
/assign @codenrhoden

2021-12-14 19:44 UTC, kkeshavamurthy commented on images/capi/ansible/roles/providers/tasks/oci.yml
> +  when: ansible_distribution == "OracleLinux"
Should this be added in the node role rather than provider?

2021-12-14 19:46 UTC, kkeshavamurthy commented on images/capi/ansible/roles/providers/tasks/oci.yml
> +  when: ansible_distribution == "Ubuntu"
Just curious, this is not done for other Ubuntu images. What's the reason for doing it for the Oracle Ubuntu images?

2021-12-14 19:48 UTC, kkeshavamurthy commented on images/capi/packer/oci/packer.json
> +        "{{user `ansible_extra_vars`}}"
Having `ansible_usr_vars` might be useful here. Helps to pass more vars when needed. Refer to other packer.json files.

2021-12-15 04:13 UTC, shyamradhakrishnan commented on images/capi/ansible/roles/providers/tasks/oci.yml
> +  when: ansible_distribution == "OracleLinux"
This is a specific step required only for OCI provided images. I dont think we should pollute the node role with this. I hope it is fine, we have similar for other providers as well - https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/ansible/roles/providers/tasks/aws.yml#L61 . Please suggest if I am missing something here.

2021-12-15 04:15 UTC, shyamradhakrishnan commented on images/capi/ansible/roles/providers/tasks/oci.yml
> +  when: ansible_distribution == "Ubuntu"
OCI provided ubuntu images has strict rules by default, which almost blocks all ingress and egress traffic. We tried this in other providers and they dont have the strict rules by default. If we dont do this, none of the communication (apiserver LB to node, etcd to etcd, node port etc) wont work. As I said, this seem to be a quirk only in the ubuntu base image provided by OCI.

2021-12-15 04:15 UTC, shyamradhakrishnan commented on images/capi/packer/oci/packer.json
> +        "{{user `ansible_extra_vars`}}"
Fixed, Thanks @kkeshavamurthy

2022-01-07 17:58 UTC, CecileRobertMichon commented
/retest

2022-01-07 18:04 UTC, CecileRobertMichon commented
pull-ova-all has a known issue (#775) but pull-azure-sigs should succeed

2022-01-07 22:33 UTC, codenrhoden requested changes
Thanks for adding this @shyamradhakrishnan !

My main comment is to get the `validate` target setup in the Makefile. That will make sure the  `pull-packer-validate` job is running against OCI as well, which right now it is not.

2022-01-07 22:33 UTC, codenrhoden commented on images/capi/Makefile
> +build-oci-all: $(OCI_BUILD_TARGETS) ## Builds all OCI image
can we also document the OCI 'validate' targets below? There should be a `validate` version of each of these.

2022-01-07 22:33 UTC, codenrhoden commented on images/capi/Makefile
> +build-oci-all: $(OCI_BUILD_TARGETS) ## Builds all OCI image
... down around line 655, add the `validate-oci-*` targets, and make sure the `-all` target lists `$(OCI_VALIDATE_TARGETS` as a dependency. That will make sure the validate CI job actually runs the validate script against OCI.

2022-01-07 22:33 UTC, codenrhoden commented on images/capi/packer/oci/packer.json
> +        "{{user `ansible_user_vars`}}"
I see this was added at @kkeshavamurthy's request. It's good thing to add, but I think we need to define the var in this file (I think the `validate` script may have picked up it's missing once it starts running). See https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/packer/ami/packer.json#L148 as an example. I'd just add it right after the ones below.

2022-01-08 11:26 UTC, shyamradhakrishnan commented
/retest

2022-01-08 12:16 UTC, shyamradhakrishnan commented
/retest

2022-01-10 06:37 UTC, shyamradhakrishnan commented on images/capi/Makefile
> +build-oci-all: $(OCI_BUILD_TARGETS) ## Builds all OCI image
Fixed

2022-01-10 06:37 UTC, shyamradhakrishnan commented on images/capi/packer/oci/packer.json
> +        "{{user `ansible_user_vars`}}"
Fixed

2022-01-10 06:38 UTC, shyamradhakrishnan commented
@codenrhoden I have added the validate targets to CI job and made the changes you suggested. The only extra I had to do was to create a private key as OCI packer validates if the private key in the auth config is valid. Hope this is OK.

2022-01-11 03:31 UTC, shyamradhakrishnan commented
/retest

2022-01-17 15:36 UTC, shyamradhakrishnan commented
/retest

2022-01-20 17:23 UTC, CecileRobertMichon reviewed
/lgtm

2022-01-20 17:55 UTC, merged