feat: allow overriding volume_type and throughput
kubernetes-sigs/image-builder pull request #826
Opened 2022-03-11 13:41 UTC by mweibel

What this PR does / why we need it:
Allows to upgrade to a gp3 volume type and accordingly specify the throughput.

2022-03-15 20:43 UTC, codenrhoden requested changes
Hi @mweibel, thanks for the enhancements here!

It looks like all the changes are to improve the Windows OS builder. There are a couple of things here that have equivalent abilities in the Linux builder, and I'd mostly like to see them be consistent with each other.

/ok-to-test

2022-03-15 20:43 UTC, codenrhoden commented on images/capi/packer/ami/packer-windows.json
> +          "volume_type": "{{ user `volume_type` }}",
this is one that is not parameterized on Linux:
https://github.com/kubernetes-sigs/image-builder/blob/7b6c9f93f45dcf28559130fb068aade0e44d5447/images/capi/packer/ami/packer.json#L22

I feel like something was there that made it required to be `gp3`, but now I can't remember... If that can be consistent with Linux (e.g. make it a variable in Linux too), that would be the ideal outcome.

2022-03-15 20:43 UTC, codenrhoden commented on images/capi/packer/ami/packer-windows.json
> +      "instance_type": "{{user `instance_type`}}",
could we make this `instance_builder_type` to match the Linux builds? `https://github.com/kubernetes-sigs/image-builder/blob/7b6c9f93f45dcf28559130fb068aade0e44d5447/images/capi/packer/ami/packer.json#L13

2022-03-17 11:44 UTC, mweibel commented on images/capi/packer/ami/packer-windows.json
> +      "instance_type": "{{user `instance_type`}}",
done :+1:

2022-03-17 11:45 UTC, mweibel commented on images/capi/packer/ami/packer-windows.json
> +          "volume_type": "{{ user `volume_type` }}",
done :+1: I also switched the default on windows to `gp3` to keep that consistent across the operating systems (switching to gp3 was actually the reason for this PR ;)). Hope this is fine.

2022-03-17 11:47 UTC, mweibel commented
I changed the requested things. The change for gp2 to gp3 for windows is something which could result in higher costs when building the image, I believe. Does that need to be pointed out in some way specifically?

2022-03-17 11:48 UTC, mweibel commented
/sig windows

is that too, I believe :)

2022-03-18 06:21 UTC, kkeshavamurthy commented
/lgtm

2022-03-28 18:25 UTC, codenrhoden approved these changes
Thanks for making the requested changes!

> I changed the requested things. The change for gp2 to gp3 for windows is something which could result in higher costs when building the image, I believe. Does that need to be pointed out in some way specifically?

It's not something we've done before... But I will be sure to point it out the next set of release notes.

/approve

2022-03-28 18:33 UTC, merged